// English is an official supported localization — preserves the meaning of ko.ts (the
// canonical source), per sdd/context/01_product_vision.md#localization-principle. Not an
// independently-authored copy.

import type { Resources } from "./shape";

export const en: Resources = {
  lifecycleStage: {
    captured: "Captured",
    structuring: "Structuring",
    scoped: "Scoped",
    validating: "Validating",
    validated: "Validated",
    "build-ready": "Build-Ready",
    archived: "Archived",
  },
  common: {
    back: "Back",
    continue: "Continue",
    cancel: "Cancel",
    create: "Create",
    archive: "Archive",
    edit: "Edit",
    loading: "Loading…",
    writeMyOwn: "Write my own",
    yourAnswer: "Your answer",
    yourAnswerPlaceholder: "Type your own answer…",
    projectLabel: "Project",
  },
  nav: {
    home: "Home",
    features: "Features",
    roadmap: "Roadmap",
    openWorkspace: "Open Workspace",
    businessStructuring: "Business Structuring",
    mvpPlanning: "MVP Planning",
    validationPlanning: "Validation Planning",
    riskMemo: "Risk Memo",
    summary: "Summary",
  },
  language: {
    korean: "한국어",
    english: "English",
  },
  landingVariants: {
    a: {
      // Problem Empathy — per sdd/context/07_landing_experiment_strategy.md
      heroTitle: "You have the idea. You just don't know where to start.",
      heroSubtitle:
        "Hypora turns a vague idea into a concrete first step — a structured workspace built for exactly this moment.",
      ctaLabel: "Take the first step",
      valueCard1Title: "From overwhelm to structure",
      valueCard1Body: "Turn a scattered idea into five clear questions you can actually answer, one at a time.",
      valueCard2Title: "See the next step clearly",
      valueCard2Body: "If you've been stalling on what to build first, draw the boundary and prioritize.",
      valueCard3Title: "Don't build on guesses",
      valueCard3Body: "Replace uncertainty with a testable plan before you write a line of code.",
      featuresTitle: "Tools to help you start",
      featuresSubtitle: "From a daunting idea to an actionable plan.",
      featureProjectManagementDesc:
        "Not sure which idea to start with? Keep every one organized in a single dashboard and work through them one at a time.",
      featureBusinessStructuringDesc:
        "If you don't know what to define first, five guided questions walk you through it in order.",
      featureMvpPlanningDesc:
        "If trying to build everything at once has you stuck, draw the boundary of a real first version.",
      featureValidationPlanningDesc: "If doubt is holding you back, turn it into a testable question and find the answer.",
      featureProjectSummaryDesc: "If you've lost track of where you are, see your readiness at a glance.",
    },
    b: {
      // Loss Aversion — per sdd/context/07_landing_experiment_strategy.md
      heroTitle: "An idea that never becomes execution disappears.",
      heroSubtitle:
        "An idea that stays in your head gets forgotten — or someone else builds it first. Structure it with Hypora now.",
      ctaLabel: "Save your idea",
      valueCard1Title: "Capture it before it's gone",
      valueCard1Body: "The moment you answer five questions, your idea stops being something you might forget.",
      valueCard2Title: "Every delay shrinks the window",
      valueCard2Body: "Without a defined scope, every decision gets postponed — prioritize now.",
      valueCard3Title: "An unvalidated assumption is a risk",
      valueCard3Body: "Before you spend time on the wrong thing, validate the assumption first.",
      featuresTitle: "Tools that turn ideas into execution",
      featuresSubtitle: "Before it disappears, turn it into structure.",
      featureProjectManagementDesc: "Don't let ideas sit forgotten — manage every one in a single dashboard.",
      featureBusinessStructuringDesc:
        "The moment you answer five questions, your idea stops living only in your head.",
      featureMvpPlanningDesc: "Without a defined scope, execution keeps slipping — draw the boundary now.",
      featureValidationPlanningDesc: "Before you spend time on an unverified assumption, check it first.",
      featureProjectSummaryDesc: "Don't lose track of progress — check your readiness at any time.",
    },
    c: {
      // Execution Confidence — per sdd/context/07_landing_experiment_strategy.md
      heroTitle: "Good execution beats a good idea.",
      heroSubtitle:
        "Hypora is a structured workspace that turns an idea into an executable plan — start executing now.",
      ctaLabel: "Start executing",
      valueCard1Title: "Turn thinking into structure",
      valueCard1Body: "Five questions turn your idea into something you can actually execute.",
      valueCard2Title: "Define scope, then move",
      valueCard2Body: "Don't wait for the perfect plan — define your first version and execute by priority.",
      valueCard3Title: "Execute while you validate",
      valueCard3Body: "Turn assumptions into testable checks, and move forward with confirmation, not guesswork.",
      featuresTitle: "Tools built for execution",
      featuresSubtitle: "Everything you need to go from idea to execution.",
      featureProjectManagementDesc: "Manage every idea you're executing on, in one dashboard.",
      featureBusinessStructuringDesc: "Structure your idea into something executable with five guided questions.",
      featureMvpPlanningDesc: "Define your scope, then execute by priority.",
      featureValidationPlanningDesc: "Turn assumptions into testable checks and execute with confirmation.",
      featureProjectSummaryDesc: "See your execution readiness at a glance.",
    },
  },
  landing: {
    heroTitle: "Turn a business idea into a validated MVP plan.",
    heroSubtitle:
      "Hypora is a structured workspace for founders — no AI, no backend, just a clear path from idea to a scoped, validated plan.",
    valueCard1Title: "Structure the idea",
    valueCard1Body: "Business Idea, Problem, Target Customer, Solution, Value Proposition — one Canvas.",
    valueCard2Title: "Scope the MVP",
    valueCard2Body: "Decide what's in your first version, and prioritize the features that matter.",
    valueCard3Title: "Validate before you build",
    valueCard3Body: "Turn assumptions into testable checks — know what's confirmed, not just hoped.",
    footer: "Hypora — structure your idea before you build it.",
    featuresTitle: "Features",
    featuresSubtitle: "Everything you need to go from idea to validated plan.",
    featureProjectManagementName: "Project Management",
    featureProjectManagementDesc: "Create and manage every business idea you're structuring, in one dashboard.",
    featureBusinessStructuringName: "Business Structuring",
    featureBusinessStructuringDesc:
      "A five-part Canvas — Business Idea, Problem, Target Customer, Solution, Value Proposition.",
    featureMvpPlanningName: "MVP Planning",
    featureMvpPlanningDesc: "Draw your scope boundary and prioritize the features that make the first version.",
    featureValidationPlanningName: "Validation Planning",
    featureValidationPlanningDesc:
      "Turn your hypothesis into testable assumptions, each with a method and a success criterion.",
    featureProjectSummaryName: "Project Summary",
    featureProjectSummaryDesc: "See readiness at a glance, and confirm when a plan is Build-Ready.",
    roadmapTitle: "Roadmap",
    roadmapSubtitle: "Hypora grows from a manual workspace into an AI Co-founder — one stage at a time.",
    roadmapV1Name: "V1 — Manual Workspace",
    roadmapV1Desc: "Structure and validate ideas manually, no AI, no backend.",
    roadmapV2Name: "V2 — AI Canvas Assistant",
    roadmapV2Desc: "AI assistance directly inside the Canvas.",
    roadmapV3Name: "V3 — Market Intelligence",
    roadmapV3Desc: "Similar service discovery, competitor research, market trends.",
    roadmapV4Name: "V4 — Go-to-Market Planning",
    roadmapV4Desc: "Marketing channel recommendations, validation experiments, early customer strategy.",
    roadmapV5Name: "V5 — AI Product Builder",
    roadmapV5Desc: "Requirement generation, SDD generation, development planning.",
  },
  dashboard: {
    title: "Your Projects",
    subtitle: "Every business idea you're structuring, in one place.",
    newProject: "New Project",
    projectNameLabel: "Project name",
    projectNamePlaceholder: "e.g. Neighborhood tool-lending app",
    emptyTitle: "No projects yet",
    emptyDescription: "Create your first project to start structuring an idea.",
    open: "Open",
    showArchived: "Show archived projects",
    hideArchived: "Hide archived projects",
    archiveConfirmTitle: "Archive this project?",
    archiveConfirmDescription:
      "It will be hidden from your default list but not deleted — you can reveal archived projects at any time.",
    loadingProjects: "Loading projects…",
  },
  businessStructuring: {
    title: "Business Structuring",
    subtitle: "One focused question at a time.",
    progressLabel: (current, total) => `Question ${current} of ${total}`,
    continueToReview: "Continue to Review",
    reviewTitle: "Review Your Business Canvas",
    reviewSubtitle: "Everything in one place — edit anything before confirming.",
    riskNotesLabel: "Risk Notes (optional)",
    riskNotesHint: "What could make this idea wrong? This doesn't block completion — it's just for your own reflection.",
    confirmAndContinue: "Confirm and Continue to MVP Planning",
    loadingProject: "Loading project…",
    guardedNotice:
      "Complete Business Structuring and MVP Planning first — Validation Planning becomes available once MVP Scope and Feature Planning are both marked complete.",
  },
  riskMemo: {
    title: "Risk Memo",
    subtitle: "Note technical risks, business risks, and what you don't know yet. Every field is optional.",
    technicalRisksLabel: "Technical Risks",
    businessRisksLabel: "Business Risks",
    openQuestionsLabel: "Open Questions",
  },
  question: {
    businessIdea: {
      title: "What's the idea, in a sentence or two?",
      presets: [
        "A subscription service that helps [audience] do [job] more easily.",
        "A marketplace connecting [group A] with [group B].",
        "A tool that automates [tedious task] for [audience].",
        "A local service that brings [thing people want] closer to [audience].",
      ],
    },
    problem: {
      title: "What problem does this solve, and for whom?",
      presets: [
        "People waste time/money because there's no easy way to [do X].",
        "Existing options are too expensive, slow, or inconvenient for [audience].",
        "There's no trusted way for [audience] to find/do [X] today.",
      ],
    },
    targetCustomer: {
      title: "Who specifically has this problem?",
      presets: [
        "Busy urban professionals",
        "Small business owners",
        "Parents of young children",
        "Students",
        "People new to a neighborhood or city",
      ],
    },
    solution: {
      title: "What are you proposing to build?",
      presets: [
        "A mobile app that connects [audience] directly with [resource].",
        "A simple web tool that automates [manual process].",
        "A curated marketplace with built-in trust/safety features.",
      ],
    },
    valueProposition: {
      title: "Why would someone choose this over alternatives?",
      presets: [
        "Saves time compared to the current alternative.",
        "Costs less than existing options.",
        "Builds trust/community in a way nothing else does.",
        "Is simply more convenient — available when and where competitors aren't.",
      ],
    },
  },
  mvpPlanning: {
    title: "MVP Planning",
    subtitle: "Define the smallest valuable version, and what it takes to build it.",
    scopeLabel: "MVP Scope",
    scopeHint: "What counts as your first version? What's explicitly out?",
    markScopeComplete: "Mark Scope complete",
    markedComplete: "Marked complete ✓",
    featurePlanningTitle: "Feature Planning",
    addFeatureLabel: "Add a feature",
    addFeaturePlaceholder: "e.g. Search by category",
    add: "Add",
    remove: "Remove",
    emptyFeaturesTitle: "No features planned yet",
    emptyFeaturesDescription: "Add your first feature above.",
    markFeaturePlanningComplete: "Mark Feature Planning complete",
    priorityMust: "Must",
    priorityShould: "Should",
    priorityCould: "Could",
    inScope: "In Scope",
    outOfScope: "Out of Scope",
    readyForValidation: "Ready for Validation Planning",
    suggestFeaturesLabel: "Suggest Features",
    suggestedFeaturesTitle: "Suggested Features",
    suggestedFeaturesEmptyNotice: "No new suggestions right now.",
    duplicateIndicator: "Already in your plan",
    featuresAddedLabel: (count) => `${count} feature${count === 1 ? "" : "s"} added`,
    historyToggleLabel: "History",
    historyTitle: "Feature History",
    historyEmptyDescription: "No Feature changes recorded yet.",
    historyCreatedLabel: "Added",
    historyRemovedLabel: "Removed",
    historyAnnotationPlaceholder: "Add an optional note…",
  },
  validationPlanning: {
    title: "Validation Planning",
    subtitle: "Turn your hypothesis into testable assumptions.",
    reopenMvpPlanning: "Reopen MVP Planning",
    addAssumptionLabel: "Add an assumption",
    addAssumptionPlaceholder: "e.g. Customers will pay $10/month for this",
    add: "Add",
    emptyTitle: "No assumptions yet",
    emptyDescription: "Add at least one assumption — an empty checklist can't be marked Validated.",
    methodLabel: "Validation method",
    methodPlaceholder: "How will you check this?",
    criterionLabel: "Success criterion",
    criterionPlaceholder: "What result counts as confirmed?",
    statusOpen: "Open",
    statusValidated: "Validated",
    statusInvalidated: "Invalidated",
    markValidated: "Mark Validated",
    markInvalidated: "Mark Invalidated",
    notReadyNotice:
      "Complete Business Structuring and MVP Planning first — Validation Planning becomes available once MVP Scope and Feature Planning are both marked complete.",
    allResolvedNotice: "All assumptions resolved — see Summary to confirm Build-Ready",
  },
  projectSummary: {
    title: "Project Summary",
    subtitle: "Readiness at a glance, aggregated from every section.",
    businessCanvasTitle: "Business Canvas",
    fieldsCompleted: (done, total) => `${done} of ${total} fields completed`,
    mvpPlanningTitle: "MVP Planning",
    mvpPlanningStatus: (scopeComplete, featureCount, planningComplete) =>
      `Scope ${scopeComplete ? "complete" : "in progress"} · ${featureCount} feature(s) planned, Feature Planning ${planningComplete ? "complete" : "in progress"}`,
    validationPlanningTitle: "Validation Planning",
    validationStatus: (resolved, total) => `${resolved} of ${total} assumptions resolved`,
    confirmBuildReady: "Confirm Build-Ready",
    isBuildReady: "This project is Build-Ready",
    blockingCanvas: "Complete all five Business Canvas fields to continue.",
    blockingScope: "Mark MVP Scope as complete.",
    blockingFeaturePlanning: "Mark Feature Planning as complete.",
    blockingValidationEmpty: "Add at least one Assumption to the Validation Checklist.",
    blockingValidationOpen: "Resolve every open Validation Checklist item.",
    blockingConfirm: "Confirm this project as Build-Ready when you're ready to act on it.",
    goToCanvas: "Go to Business Canvas",
    goToMvpPlanning: "Go to MVP Planning",
    goToValidationPlanning: "Go to Validation Planning",
  },
  aiAssistant: {
    askAiLabel: "Ask AI for a suggestion",
    aiTag: "AI",
    loadingLabel: "Getting a suggestion…",
    acceptLabel: "Accept",
    rejectLabel: "Dismiss",
    regenerateLabel: "Try another",
    retryLabel: "Retry",
    appliedLabel: "Applied",
    failureGeneric: "Couldn't get a suggestion right now. You can keep writing your own answer.",
    failureTimeout: "This is taking longer than expected. You can retry, or keep writing your own answer.",
    failureRateLimited: "AI assistance needs a moment. You can retry shortly, or keep writing your own answer.",
    failureUnavailable: "AI assistance isn't available right now. You can keep writing your own answer.",
    failureSafetyRefusal: "No suggestion is available for this request. You can keep writing your own answer.",
  },
  errors: {
    projectNotFound: "Project not found.",
    saveFailed: "Your last change couldn't be saved. Please try again.",
  },
};
