// English is an official supported localization — preserves the meaning of ko.ts (the
// canonical source), per sdd/context/01_product_vision.md#localization-principle. Not an
// independently-authored copy.

import type { Resources } from "./shape";

export const en: Resources = {
  lifecycleStage: {
    captured: "Captured",
    structuring: "Structuring",
    scoped: "Scoped",
    validating: "Validating",
    validated: "Validated",
    "build-ready": "Build-Ready",
    archived: "Archived",
  },
  common: {
    back: "Back",
    continue: "Continue",
    cancel: "Cancel",
    create: "Create",
    archive: "Archive",
    edit: "Edit",
    loading: "Loading…",
    writeMyOwn: "Write my own",
    yourAnswer: "Your answer",
    yourAnswerPlaceholder: "Type your own answer…",
    projectLabel: "Project",
  },
  nav: {
    home: "Home",
    features: "Features",
    openWorkspace: "Open Workspace",
    businessStructuring: "Business Structuring",
    mvpPlanning: "MVP Planning",
    validationPlanning: "Validation Planning",
    riskMemo: "Risk Memo",
    summary: "Summary",
  },
  language: {
    korean: "한국어",
    english: "English",
  },
  landingVariants: {
    a: {
      // Problem Empathy — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "Manual workspace — V1 runs with no AI",
      heroTitle: "You have the idea. You just don't know where to start.",
      heroSubtitle:
        "Hypora turns a vague idea into a concrete first step — a structured workspace built for exactly this moment.",
      ctaLabel: "Take the first step",
      gapEyebrow: "Somewhere in between",
      gapTitle: "There's a place notes and execution tools both leave empty.",
      gapSupport: "Plenty of people quietly get stuck right here. You're not the only one.",
      gapNoteToolBody: "You can write freely, but it won't structure your thinking for you.",
      gapExecToolBody: "It assumes your scope is already decided, and just helps you manage it.",
      gapHyporaBody: "In between, we fill in the step before an idea becomes an executable plan.",
      mechanismTitle: "You don't have to figure this out alone. Just answer one thing at a time.",
      mechanismSupport: "No framework to learn in advance — structure emerges naturally as you answer.",
      mechanismPoint1: "You face one question at a time",
      mechanismPoint2: "Pick a suggested option, or write your own",
      mechanismPoint3: "Progress is always visible, and your answers stay put even if you go back",
      svEyebrow: "Organizing vs. Validating",
      svTitle: "Organizing and judging are both yours to do — just never alone.",
      svSupport: "The two steps are clearly different, and you walk through them together, in order.",
      svStructuringLabel: "Organizing",
      svStructuringBody:
        "Business Idea, Problem, Target Customer, Solution, Value Proposition — you organize it yourself, one question at a time.",
      svValidatingLabel: "Validating",
      svValidatingBody: "You mark each assumption yourself, honestly. Nothing gets confirmed automatically.",
      svNote: "\"Validated\" always means you marked it yourself — never an automated judgment or outside certification.",
      notTitle: "A space for one idea at a time. A little different from the tools that come to mind.",
      notRow1Label: "Not a note-taking app",
      notRow1Desc: "Structure isn't optional here — it's the default. That structure is this tool's whole value.",
      notRow2Label: "Not a project-management tool",
      notRow2Desc: "It stops before execution. No sprints, no tickets.",
      notRow3Label: "Not a tool that writes it for you",
      notRow3Desc: "V1 has no AI at all. Even later, it will only ever suggest.",
      notRow4Label: "Not a team tool yet",
      notRow4Desc: "Right now it's built for one person going deep on one idea.",
      notScope: "If you found yourself confusing this with those other tools, that's fair — Hypora was built to be different on purpose.",
      visionTitle: "The journey you started here keeps growing together with you.",
      visionSupport:
        "Today, it helps you organize your thinking. Later, it will help you carry that plan into execution too — the decision stays yours, always.",
      visionThemes: [
        "So an idea can become something real",
        "Staying with you even after your thinking is organized",
        "So organized thinking leads to confident execution",
      ],
      closingTitle: "Take it slow — start one step at a time.",
      closingLede: "All you have to do is start by answering one question.",
      microCopy: "No account needed. No signup. Your project stays only in this browser, only with you.",
      secondaryLinkLabel: "Not ready yet? See Hypora's direction first →",
      featuresTitle: "Tools to help you start",
      featuresSubtitle: "From a daunting idea to an actionable plan.",
      featureProjectManagementDesc:
        "Not sure which idea to start with? Keep every one organized in a single dashboard and work through them one at a time.",
      featureBusinessStructuringDesc:
        "If you don't know what to define first, five guided questions walk you through it in order.",
      featureMvpPlanningDesc:
        "If trying to build everything at once has you stuck, draw the boundary of a real first version.",
      featureValidationPlanningDesc: "If doubt is holding you back, turn it into a testable question and find the answer.",
      featureProjectSummaryDesc: "If you've lost track of where you are, see your readiness at a glance.",
    },
    b: {
      // Loss Aversion — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "Leave it unexecuted, and it disappears",
      heroTitle: "An idea that never becomes execution disappears.",
      heroSubtitle:
        "An idea that stays in your head gets forgotten — or someone else builds it first. Structure it with Hypora now.",
      ctaLabel: "Save your idea",
      gapEyebrow: "What's slipping through",
      gapTitle: "Notes don't organize your thinking, and execution tools only help once it's already too late.",
      gapSupport: "An idea left unstructured loses a little priority every single day.",
      gapNoteToolBody: "You can write freely, but if it's left alone, it just gets forgotten.",
      gapExecToolBody: "It assumes the scope is already decided — useless if it isn't.",
      gapHyporaBody: "In between, we turn it into structure before the idea disappears.",
      mechanismTitle: "Five questions are enough. Leave a structure behind before it's too late.",
      mechanismSupport:
        "You don't need to know a framework. If you don't answer now, this thought might not come back.",
      mechanismPoint1: "One question at a time — answer right away instead of putting it off",
      mechanismPoint2: "Pick an option or write your own — without losing time",
      mechanismPoint3: "Progress stays saved — you won't lose what you've thought through so far",
      svEyebrow: "Structuring vs. Validating",
      svTitle: "An unchecked assumption becomes a bigger loss later.",
      svSupport: "If you don't validate now, you'll only find out after you've already spent time in the wrong direction.",
      svStructuringLabel: "Structuring",
      svStructuringBody: "Organize your idea now by answering questions — put it off, and it fades.",
      svValidatingLabel: "Validating",
      svValidatingBody: "Check each assumption yourself, one at a time. An unchecked assumption costs more later.",
      svNote:
        "\"Validated\" means you checked it yourself — skip that step, and you'll pay for it later.",
      notTitle: "Fills in exactly what other tools miss.",
      notRow1Label: "Not a note-taking app",
      notRow1Desc: "If you only write it down, you'll eventually stop looking at it and forget it.",
      notRow2Label: "Not a project-management tool",
      notRow2Desc: "There's nothing to manage while the scope is still undecided.",
      notRow3Label: "Not a tool that writes it for you",
      notRow3Desc: "V1 runs with no AI — don't lose time waiting for one.",
      notRow4Label: "Not a team tool yet",
      notRow4Desc: "Right now the focus is protecting one person's idea first.",
      notScope:
        "If you were using a different category of tool, that may be exactly where your idea was slipping away.",
      visionTitle: "The structure you capture today stays with you as it grows.",
      visionSupport:
        "Today, it helps keep your idea from fading. Later, it will help carry that plan through to execution too — the decision stays yours, always.",
      visionThemes: [
        "So an idea never fades before it's finished",
        "So organized thinking carries through to execution",
        "Growing right alongside you",
      ],
      closingTitle: "Before it's too late, hold onto your idea now.",
      closingLede: "Every extra day it stays unstructured, it fades a little more.",
      microCopy: "No account or signup needed. Instead of waiting, start right now.",
      secondaryLinkLabel: "Still hesitating? See where Hypora is headed first →",
      featuresTitle: "Tools that turn ideas into execution",
      featuresSubtitle: "Before it disappears, turn it into structure.",
      featureProjectManagementDesc: "Don't let ideas sit forgotten — manage every one in a single dashboard.",
      featureBusinessStructuringDesc:
        "The moment you answer five questions, your idea stops living only in your head.",
      featureMvpPlanningDesc: "Without a defined scope, execution keeps slipping — draw the boundary now.",
      featureValidationPlanningDesc: "Before you spend time on an unverified assumption, check it first.",
      featureProjectSummaryDesc: "Don't lose track of progress — check your readiness at any time.",
    },
    c: {
      // Execution Confidence — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "Start executing right now",
      heroTitle: "Good execution beats a good idea.",
      heroSubtitle:
        "Hypora is a structured workspace that turns an idea into an executable plan — start executing now.",
      ctaLabel: "Start executing",
      gapEyebrow: "The difference",
      gapTitle: "The difference between people who only think and people who execute is structure — nothing else.",
      gapSupport:
        "Notes don't organize your thinking, and execution tools only manage a scope that's already decided. Filling that gap is where execution starts.",
      gapNoteToolBody: "You can write freely, but it doesn't lead to execution.",
      gapExecToolBody: "It assumes the scope is already decided.",
      gapHyporaBody: "We turn structure into an executable plan — so you can start right now.",
      mechanismTitle: "The moment you answer a question, your plan becomes something executable.",
      mechanismSupport: "You don't need to know a framework. Every answer becomes structure immediately.",
      mechanismPoint1: "Focus on one question — it leads straight to the next step",
      mechanismPoint2: "Pick an option or write your own — without slowing down",
      mechanismPoint3: "Progress builds up — pick back up right where you left off",
      svEyebrow: "Structuring vs. Validating",
      svTitle: "Structuring is the starting line; validating is the next step toward execution.",
      svSupport: "You do both yourself, but each one has a clear, distinct role.",
      svStructuringLabel: "Structuring",
      svStructuringBody: "Build your plan by answering questions — the first step toward execution.",
      svValidatingLabel: "Validating",
      svValidatingBody: "Check each assumption yourself, one at a time, to judge whether you're ready to execute.",
      svNote: "\"Validated\" means you personally judged it ready to act on.",
      notTitle: "If you want real execution, you need a different choice than these tools.",
      notRow1Label: "Not a note-taking app",
      notRow1Desc: "Writing it down alone doesn't lead to execution.",
      notRow2Label: "Not a project-management tool",
      notRow2Desc: "It stops before the scope is decided — managing execution comes after that.",
      notRow3Label: "Not a tool that writes it for you",
      notRow3Desc: "V1 runs with no AI. Even later, AI will only ever suggest — you stay in charge of execution.",
      notRow4Label: "Not a team tool yet",
      notRow4Desc: "Right now the focus is helping one person build an executable plan fast.",
      notScope:
        "If you want structure that leads to execution, not a tool where you just sit and think, start here.",
      visionTitle: "From structure to confident execution, Hypora stays with you the whole way.",
      visionSupport:
        "Today, it helps you build a plan. Later, it will help you execute that plan too — you always set the direction.",
      visionThemes: [
        "So thinking becomes an executable plan",
        "So a plan carries through to confident execution",
        "Growing with you at every step of execution",
      ],
      closingTitle: "Start executing, right now.",
      closingLede: "The moment you answer a question, your plan starts moving.",
      microCopy: "No account or signup needed. Answer the first question right now.",
      secondaryLinkLabel: "Want to see where this is headed first? →",
      featuresTitle: "Tools built for execution",
      featuresSubtitle: "Everything you need to go from idea to execution.",
      featureProjectManagementDesc: "Manage every idea you're executing on, in one dashboard.",
      featureBusinessStructuringDesc: "Structure your idea into something executable with five guided questions.",
      featureMvpPlanningDesc: "Define your scope, then execute by priority.",
      featureValidationPlanningDesc: "Turn assumptions into testable checks and execute with confirmation.",
      featureProjectSummaryDesc: "See your execution readiness at a glance.",
    },
  },
  landing: {
    footer: "Hypora — structure your idea before you build it.",
    featuresTitle: "Features",
    featuresSubtitle: "Everything you need to go from idea to validated plan.",
    featureProjectManagementName: "Project Management",
    featureProjectManagementDesc: "Create and manage every business idea you're structuring, in one dashboard.",
    featureBusinessStructuringName: "Business Structuring",
    featureBusinessStructuringDesc:
      "A five-part Canvas — Business Idea, Problem, Target Customer, Solution, Value Proposition.",
    featureMvpPlanningName: "MVP Planning",
    featureMvpPlanningDesc: "Draw your scope boundary and prioritize the features that make the first version.",
    featureValidationPlanningName: "Validation Planning",
    featureValidationPlanningDesc:
      "Turn your hypothesis into testable assumptions, each with a method and a success criterion.",
    featureProjectSummaryName: "Project Summary",
    featureProjectSummaryDesc: "See readiness at a glance, and confirm when a plan is Build-Ready.",
    gapNoteToolTag: "Note tools",
    gapExecToolTag: "Execution tools",
    gapHyporaTag: "Hypora",
    mechanismQuestionLabel: "Question 3 / 5",
    mechanismQuestionText: "Who is this idea actually for?",
    mechanismChip1: "Busy professionals",
    mechanismChip2: "Early-stage founders",
    mechanismChip3: "Small teams",
    mechanismChip4: "Write my own…",
    mechanismResultLabel: "Saved to your Canvas → Target Customer ✓",
    svCheckOpenLabel: "“Customers will pay for this problem” — still an assumption",
    svCheckDoneLabel: "“The problem is real” — validated by you",
    mechanismEyebrow: "How Hypora Thinks",
    notEyebrow: "Hypora Is",
    visionEyebrow: "Hypora's Direction",
  },
  dashboard: {
    title: "Your Projects",
    subtitle: "Every business idea you're structuring, in one place.",
    newProject: "New Project",
    projectNameLabel: "Project name",
    projectNamePlaceholder: "e.g. Neighborhood tool-lending app",
    emptyTitle: "No projects yet",
    emptyDescription: "Create your first project to start structuring an idea.",
    open: "Open",
    showArchived: "Show archived projects",
    hideArchived: "Hide archived projects",
    archiveConfirmTitle: "Archive this project?",
    archiveConfirmDescription:
      "It will be hidden from your default list but not deleted — you can reveal archived projects at any time.",
    loadingProjects: "Loading projects…",
  },
  businessStructuring: {
    title: "Business Structuring",
    subtitle: "One focused question at a time.",
    progressLabel: (current, total) => `Question ${current} of ${total}`,
    continueToReview: "Continue to Review",
    reviewTitle: "Review Your Business Canvas",
    reviewSubtitle: "Everything in one place — edit anything before confirming.",
    riskNotesLabel: "Risk Notes (optional)",
    riskNotesHint: "What could make this idea wrong? This doesn't block completion — it's just for your own reflection.",
    confirmAndContinue: "Confirm and Continue to MVP Planning",
    loadingProject: "Loading project…",
    guardedNotice:
      "Complete Business Structuring and MVP Planning first — Validation Planning becomes available once MVP Scope and Feature Planning are both marked complete.",
  },
  riskMemo: {
    title: "Risk Memo",
    subtitle: "Note technical risks, business risks, and what you don't know yet. Every field is optional.",
    technicalRisksLabel: "Technical Risks",
    businessRisksLabel: "Business Risks",
    openQuestionsLabel: "Open Questions",
  },
  question: {
    businessIdea: {
      title: "What's the idea, in a sentence or two?",
      presets: [
        "A subscription service that helps [audience] do [job] more easily.",
        "A marketplace connecting [group A] with [group B].",
        "A tool that automates [tedious task] for [audience].",
        "A local service that brings [thing people want] closer to [audience].",
      ],
    },
    problem: {
      title: "What problem does this solve, and for whom?",
      presets: [
        "People waste time/money because there's no easy way to [do X].",
        "Existing options are too expensive, slow, or inconvenient for [audience].",
        "There's no trusted way for [audience] to find/do [X] today.",
      ],
    },
    targetCustomer: {
      title: "Who specifically has this problem?",
      presets: [
        "Busy urban professionals",
        "Small business owners",
        "Parents of young children",
        "Students",
        "People new to a neighborhood or city",
      ],
    },
    solution: {
      title: "What are you proposing to build?",
      presets: [
        "A mobile app that connects [audience] directly with [resource].",
        "A simple web tool that automates [manual process].",
        "A curated marketplace with built-in trust/safety features.",
      ],
    },
    valueProposition: {
      title: "Why would someone choose this over alternatives?",
      presets: [
        "Saves time compared to the current alternative.",
        "Costs less than existing options.",
        "Builds trust/community in a way nothing else does.",
        "Is simply more convenient — available when and where competitors aren't.",
      ],
    },
  },
  mvpPlanning: {
    title: "MVP Planning",
    subtitle: "Define the smallest valuable version, and what it takes to build it.",
    scopeLabel: "MVP Scope",
    scopeHint: "What counts as your first version? What's explicitly out?",
    markScopeComplete: "Mark Scope complete",
    markedComplete: "Marked complete ✓",
    featurePlanningTitle: "Feature Planning",
    addFeatureLabel: "Add a feature",
    addFeaturePlaceholder: "e.g. Search by category",
    add: "Add",
    remove: "Remove",
    emptyFeaturesTitle: "No features planned yet",
    emptyFeaturesDescription: "Add your first feature above.",
    markFeaturePlanningComplete: "Mark Feature Planning complete",
    priorityMust: "Must",
    priorityShould: "Should",
    priorityCould: "Could",
    inScope: "In Scope",
    outOfScope: "Out of Scope",
    readyForValidation: "Ready for Validation Planning",
    suggestFeaturesLabel: "Suggest Features",
    suggestedFeaturesTitle: "Suggested Features",
    suggestedFeaturesEmptyNotice: "No new suggestions right now.",
    duplicateIndicator: "Already in your plan",
    featuresAddedLabel: (count) => `${count} feature${count === 1 ? "" : "s"} added`,
    historyToggleLabel: "History",
    historyTitle: "Feature History",
    historyEmptyDescription: "No Feature changes recorded yet.",
    historyCreatedLabel: "Added",
    historyRemovedLabel: "Removed",
    historyAnnotationPlaceholder: "Add an optional note…",
  },
  validationPlanning: {
    title: "Validation Planning",
    subtitle: "Turn your hypothesis into testable assumptions.",
    reopenMvpPlanning: "Reopen MVP Planning",
    addAssumptionLabel: "Add an assumption",
    addAssumptionPlaceholder: "e.g. Customers will pay $10/month for this",
    add: "Add",
    emptyTitle: "No assumptions yet",
    emptyDescription: "Add at least one assumption — an empty checklist can't be marked Validated.",
    methodLabel: "Validation method",
    methodPlaceholder: "How will you check this?",
    criterionLabel: "Success criterion",
    criterionPlaceholder: "What result counts as confirmed?",
    statusOpen: "Open",
    statusValidated: "Validated",
    statusInvalidated: "Invalidated",
    markValidated: "Mark Validated",
    markInvalidated: "Mark Invalidated",
    notReadyNotice:
      "Complete Business Structuring and MVP Planning first — Validation Planning becomes available once MVP Scope and Feature Planning are both marked complete.",
    allResolvedNotice: "All assumptions resolved — see Summary to confirm Build-Ready",
  },
  projectSummary: {
    title: "Project Summary",
    subtitle: "Readiness at a glance, aggregated from every section.",
    businessCanvasTitle: "Business Canvas",
    fieldsCompleted: (done, total) => `${done} of ${total} fields completed`,
    mvpPlanningTitle: "MVP Planning",
    mvpPlanningStatus: (scopeComplete, featureCount, planningComplete) =>
      `Scope ${scopeComplete ? "complete" : "in progress"} · ${featureCount} feature(s) planned, Feature Planning ${planningComplete ? "complete" : "in progress"}`,
    validationPlanningTitle: "Validation Planning",
    validationStatus: (resolved, total) => `${resolved} of ${total} assumptions resolved`,
    confirmBuildReady: "Confirm Build-Ready",
    isBuildReady: "This project is Build-Ready",
    blockingCanvas: "Complete all five Business Canvas fields to continue.",
    blockingScope: "Mark MVP Scope as complete.",
    blockingFeaturePlanning: "Mark Feature Planning as complete.",
    blockingValidationEmpty: "Add at least one Assumption to the Validation Checklist.",
    blockingValidationOpen: "Resolve every open Validation Checklist item.",
    blockingConfirm: "Confirm this project as Build-Ready when you're ready to act on it.",
    goToCanvas: "Go to Business Canvas",
    goToMvpPlanning: "Go to MVP Planning",
    goToValidationPlanning: "Go to Validation Planning",
    summaryCardTitle: "Summary",
    summaryNotGenerated: "A synthesized summary will be generated automatically once your Canvas, MVP Plan, and Validation Plan are complete.",
    summaryGenerating: "Generating your project summary…",
    summaryOutOfSyncBadge: "Out of sync",
    summaryOutOfSyncNotice: "This summary was written before your latest changes. It's still shown below, unchanged, until you choose to sync it.",
    syncSummaryButton: "Sync Summary",
    syncDialogTitle: "Synchronize Summary",
    syncDialogAsIsLabel: "As-Is (currently saved)",
    syncDialogToBeLabel: "To-Be (draft)",
    syncDialogToBeEmptyHint: "Press \"AI Summary Update\" to draft an updated summary, then edit it freely before applying.",
    aiSummaryUpdateButton: "AI Summary Update",
    applyButton: "Apply",
  },
  aiAssistant: {
    askAiLabel: "Ask AI for a suggestion",
    aiTag: "AI",
    loadingLabel: "Getting a suggestion…",
    acceptLabel: "Accept",
    rejectLabel: "Dismiss",
    regenerateLabel: "Try another",
    retryLabel: "Retry",
    appliedLabel: "Applied",
    failureGeneric: "Couldn't get a suggestion right now. You can keep writing your own answer.",
    failureTimeout: "This is taking longer than expected. You can retry, or keep writing your own answer.",
    failureRateLimited: "AI assistance needs a moment. You can retry shortly, or keep writing your own answer.",
    failureUnavailable: "AI assistance isn't available right now. You can keep writing your own answer.",
    failureSafetyRefusal: "No suggestion is available for this request. You can keep writing your own answer.",
  },
  errors: {
    projectNotFound: "Project not found.",
    saveFailed: "Your last change couldn't be saved. Please try again.",
  },
};
