// Korean is the canonical source language — authored first, per
// sdd/context/01_product_vision.md#localization-principle. English (en.ts) is derived from
// this file to preserve meaning, not authored independently.

import type { Resources } from "./shape";

export const ko: Resources = {
  lifecycleStage: {
    captured: "시작 전",
    structuring: "구조화 중",
    scoped: "범위 설정됨",
    validating: "검증 중",
    validated: "검증됨",
    "build-ready": "빌드 준비 완료",
    archived: "보관됨",
  },
  common: {
    back: "이전",
    continue: "계속",
    cancel: "취소",
    create: "만들기",
    archive: "보관",
    edit: "수정",
    loading: "불러오는 중…",
    writeMyOwn: "직접 입력",
    yourAnswer: "답변",
    yourAnswerPlaceholder: "직접 답변을 입력하세요…",
    projectLabel: "프로젝트",
  },
  nav: {
    home: "홈",
    features: "기능",
    roadmap: "로드맵",
    openWorkspace: "워크스페이스 열기",
    businessStructuring: "비즈니스 구조화",
    mvpPlanning: "MVP 계획",
    validationPlanning: "검증 계획",
    riskMemo: "리스크 메모",
    summary: "요약",
  },
  language: {
    korean: "한국어",
    english: "English",
  },
  landing: {
    heroTitle: "비즈니스 아이디어를 검증된 MVP 계획으로",
    heroSubtitle:
      "Hypora는 창업자를 위한 구조화된 워크스페이스입니다 — AI도, 백엔드도 없이, 아이디어에서 범위가 정해지고 검증된 계획까지 명확한 경로를 제공합니다.",
    valueCard1Title: "아이디어 구조화",
    valueCard1Body: "비즈니스 아이디어, 문제, 타겟 고객, 솔루션, 가치 제안 — 하나의 캔버스로.",
    valueCard2Title: "MVP 범위 설정",
    valueCard2Body: "첫 번째 버전에 무엇을 포함할지 결정하고, 중요한 기능의 우선순위를 정하세요.",
    valueCard3Title: "빌드하기 전에 검증",
    valueCard3Body: "가정을 테스트 가능한 항목으로 바꾸세요 — 희망이 아니라 확인된 것을 아세요.",
    footer: "Hypora — 만들기 전에 아이디어를 구조화하세요.",
    featuresTitle: "기능",
    featuresSubtitle: "아이디어에서 검증된 계획까지 필요한 모든 것.",
    featureProjectManagementName: "프로젝트 관리",
    featureProjectManagementDesc: "구조화 중인 모든 비즈니스 아이디어를 하나의 대시보드에서 만들고 관리하세요.",
    featureBusinessStructuringName: "비즈니스 구조화",
    featureBusinessStructuringDesc: "5개 항목의 캔버스 — 비즈니스 아이디어, 문제, 타겟 고객, 솔루션, 가치 제안.",
    featureMvpPlanningName: "MVP 계획",
    featureMvpPlanningDesc: "범위 경계를 정하고 첫 버전을 구성할 기능의 우선순위를 정하세요.",
    featureValidationPlanningName: "검증 계획",
    featureValidationPlanningDesc: "가설을 테스트 가능한 가정으로 바꾸고, 각각에 방법과 성공 기준을 부여하세요.",
    featureProjectSummaryName: "프로젝트 요약",
    featureProjectSummaryDesc: "한눈에 준비 상태를 확인하고, 계획이 빌드 준비 완료되었을 때 확정하세요.",
    roadmapTitle: "로드맵",
    roadmapSubtitle: "Hypora는 수동 워크스페이스에서 AI 공동창업자로 — 한 단계씩 성장합니다.",
    roadmapV1Name: "V1 — 수동 워크스페이스",
    roadmapV1Desc: "AI도 백엔드도 없이 수동으로 아이디어를 구조화하고 검증합니다.",
    roadmapV2Name: "V2 — AI 캔버스 어시스턴트",
    roadmapV2Desc: "캔버스 안에서 바로 AI의 도움을 받습니다.",
    roadmapV3Name: "V3 — 시장 인텔리전스",
    roadmapV3Desc: "유사 서비스 발견, 경쟁사 조사, 시장 트렌드.",
    roadmapV4Name: "V4 — 고투마켓 계획",
    roadmapV4Desc: "마케팅 채널 추천, 검증 실험, 초기 고객 전략.",
    roadmapV5Name: "V5 — AI 프로덕트 빌더",
    roadmapV5Desc: "요구사항 생성, SDD 생성, 개발 계획.",
  },
  dashboard: {
    title: "내 프로젝트",
    subtitle: "구조화 중인 모든 비즈니스 아이디어를 한곳에서.",
    newProject: "새 프로젝트",
    projectNameLabel: "프로젝트 이름",
    projectNamePlaceholder: "예: 동네 도구 대여 앱",
    emptyTitle: "아직 프로젝트가 없습니다",
    emptyDescription: "첫 프로젝트를 만들어 아이디어 구조화를 시작하세요.",
    open: "열기",
    showArchived: "보관된 프로젝트 보기",
    hideArchived: "보관된 프로젝트 숨기기",
    archiveConfirmTitle: "이 프로젝트를 보관하시겠습니까?",
    archiveConfirmDescription:
      "기본 목록에서 숨겨지지만 삭제되지는 않습니다 — 언제든지 보관된 프로젝트를 다시 볼 수 있습니다.",
    loadingProjects: "프로젝트를 불러오는 중…",
  },
  businessStructuring: {
    title: "비즈니스 구조화",
    subtitle: "한 번에 하나의 질문에 집중하세요.",
    progressLabel: (current, total) => `${total}개 중 ${current}번째 질문`,
    continueToReview: "검토로 이동",
    reviewTitle: "비즈니스 캔버스 검토",
    reviewSubtitle: "모든 내용을 한곳에서 — 확정하기 전에 무엇이든 수정하세요.",
    riskNotesLabel: "리스크 메모 (선택)",
    riskNotesHint: "이 아이디어가 실패할 수 있는 이유는 무엇인가요? 완료를 막지 않으며, 스스로의 성찰을 위한 것입니다.",
    confirmAndContinue: "확인하고 MVP 계획으로 이동",
    loadingProject: "프로젝트를 불러오는 중…",
    guardedNotice: "먼저 비즈니스 구조화와 MVP 계획을 완료하세요 — MVP 범위와 기능 계획이 모두 완료되면 검증 계획을 사용할 수 있습니다.",
  },
  riskMemo: {
    title: "리스크 메모",
    subtitle: "기술적 리스크, 비즈니스 리스크, 그리고 아직 알지 못하는 것들을 기록하세요. 모든 항목은 선택 사항입니다.",
    technicalRisksLabel: "기술적 리스크",
    businessRisksLabel: "비즈니스 리스크",
    openQuestionsLabel: "아직 모르는 것",
  },
  question: {
    businessIdea: {
      title: "아이디어를 한두 문장으로 설명해 주세요.",
      presets: [
        "[대상]이 [일]을 더 쉽게 할 수 있도록 돕는 구독 서비스.",
        "[그룹 A]와 [그룹 B]를 연결하는 마켓플레이스.",
        "[대상]을 위해 [번거로운 작업]을 자동화하는 도구.",
        "[원하는 것]을 [대상]에게 더 가까이 가져다주는 지역 서비스.",
      ],
    },
    problem: {
      title: "어떤 문제를 해결하려고 하나요? 누구의 문제인가요?",
      presets: [
        "[X]를 쉽게 할 방법이 없어서 사람들이 시간이나 돈을 낭비하고 있습니다.",
        "기존 옵션은 [대상]에게 너무 비싸거나, 느리거나, 불편합니다.",
        "[대상]이 오늘날 [X]를 찾거나 할 수 있는 신뢰할 수 있는 방법이 없습니다.",
      ],
    },
    targetCustomer: {
      title: "구체적으로 누가 이 문제를 겪고 있나요?",
      presets: ["바쁜 도시 직장인", "소상공인", "어린 자녀를 둔 부모", "학생", "새로운 동네나 도시로 이사한 사람"],
    },
    solution: {
      title: "무엇을 만들려고 하나요?",
      presets: [
        "[대상]을 [자원]과 직접 연결하는 모바일 앱.",
        "[수동 프로세스]를 자동화하는 간단한 웹 도구.",
        "신뢰·안전 기능이 내장된 큐레이션 마켓플레이스.",
      ],
    },
    valueProposition: {
      title: "사람들이 다른 대안 대신 이것을 선택하는 이유는 무엇인가요?",
      presets: [
        "기존 대안보다 시간을 절약해 줍니다.",
        "기존 옵션보다 비용이 적게 듭니다.",
        "다른 어떤 것도 하지 못하는 방식으로 신뢰와 커뮤니티를 만듭니다.",
        "경쟁자가 제공하지 못하는 때와 장소에서 이용할 수 있어 더 편리합니다.",
      ],
    },
  },
  mvpPlanning: {
    title: "MVP 계획",
    subtitle: "가장 작은 가치 있는 버전과 이를 만드는 데 필요한 것을 정의하세요.",
    scopeLabel: "MVP 범위",
    scopeHint: "첫 버전에 무엇이 포함되나요? 명시적으로 제외되는 것은 무엇인가요?",
    markScopeComplete: "범위 완료 표시",
    markedComplete: "완료 표시됨 ✓",
    featurePlanningTitle: "기능 계획",
    addFeatureLabel: "기능 추가",
    addFeaturePlaceholder: "예: 카테고리별 검색",
    add: "추가",
    remove: "제거",
    emptyFeaturesTitle: "아직 계획된 기능이 없습니다",
    emptyFeaturesDescription: "위에서 첫 번째 기능을 추가하세요.",
    markFeaturePlanningComplete: "기능 계획 완료 표시",
    priorityMust: "필수",
    priorityShould: "권장",
    priorityCould: "선택",
    inScope: "범위 포함",
    outOfScope: "범위 제외",
    readyForValidation: "검증 계획 준비 완료",
    suggestFeaturesLabel: "기능 제안받기",
    suggestedFeaturesTitle: "제안된 기능",
    suggestedFeaturesEmptyNotice: "지금은 새로운 제안이 없습니다.",
    duplicateIndicator: "이미 계획에 있음",
    featuresAddedLabel: (count) => `기능 ${count}개 추가됨`,
    historyToggleLabel: "히스토리",
    historyTitle: "기능 히스토리",
    historyEmptyDescription: "아직 기록된 기능 변경 사항이 없습니다.",
    historyCreatedLabel: "추가됨",
    historyRemovedLabel: "제거됨",
    historyAnnotationPlaceholder: "선택적으로 메모를 추가하세요…",
  },
  validationPlanning: {
    title: "검증 계획",
    subtitle: "가설을 테스트 가능한 가정으로 바꾸세요.",
    reopenMvpPlanning: "MVP 계획 다시 열기",
    addAssumptionLabel: "가정 추가",
    addAssumptionPlaceholder: "예: 고객이 이 서비스에 월 1만원을 지불할 것이다",
    add: "추가",
    emptyTitle: "아직 가정이 없습니다",
    emptyDescription: "최소 하나의 가정을 추가하세요 — 빈 체크리스트는 검증 완료로 표시할 수 없습니다.",
    methodLabel: "검증 방법",
    methodPlaceholder: "이것을 어떻게 확인할 건가요?",
    criterionLabel: "성공 기준",
    criterionPlaceholder: "어떤 결과가 나오면 확인된 것으로 볼 건가요?",
    statusOpen: "미해결",
    statusValidated: "검증됨",
    statusInvalidated: "반증됨",
    markValidated: "검증됨으로 표시",
    markInvalidated: "반증됨으로 표시",
    notReadyNotice: "먼저 비즈니스 구조화와 MVP 계획을 완료하세요 — MVP 범위와 기능 계획이 모두 완료되면 검증 계획을 사용할 수 있습니다.",
    allResolvedNotice: "모든 가정이 해결되었습니다 — 빌드 준비 확정을 위해 요약을 확인하세요",
  },
  projectSummary: {
    title: "프로젝트 요약",
    subtitle: "모든 항목에서 종합한, 한눈에 보는 준비 상태.",
    businessCanvasTitle: "비즈니스 캔버스",
    fieldsCompleted: (done, total) => `${total}개 중 ${done}개 항목 완료`,
    mvpPlanningTitle: "MVP 계획",
    mvpPlanningStatus: (scopeComplete, featureCount, planningComplete) =>
      `범위 ${scopeComplete ? "완료" : "진행 중"} · 기능 ${featureCount}개 계획됨, 기능 계획 ${planningComplete ? "완료" : "진행 중"}`,
    validationPlanningTitle: "검증 계획",
    validationStatus: (resolved, total) => `${total}개 중 ${resolved}개 가정 해결됨`,
    confirmBuildReady: "빌드 준비 완료 확정",
    isBuildReady: "이 프로젝트는 빌드 준비가 완료되었습니다",
    blockingCanvas: "계속하려면 비즈니스 캔버스의 5개 항목을 모두 완료하세요.",
    blockingScope: "MVP 범위를 완료로 표시하세요.",
    blockingFeaturePlanning: "기능 계획을 완료로 표시하세요.",
    blockingValidationEmpty: "검증 체크리스트에 최소 하나의 가정을 추가하세요.",
    blockingValidationOpen: "모든 미해결 검증 체크리스트 항목을 해결하세요.",
    blockingConfirm: "실행할 준비가 되면 이 프로젝트를 빌드 준비 완료로 확정하세요.",
    goToCanvas: "비즈니스 캔버스로 이동",
    goToMvpPlanning: "MVP 계획으로 이동",
    goToValidationPlanning: "검증 계획으로 이동",
  },
  aiAssistant: {
    askAiLabel: "AI에게 제안 받기",
    aiTag: "AI",
    loadingLabel: "제안을 가져오는 중…",
    acceptLabel: "적용",
    rejectLabel: "닫기",
    regenerateLabel: "다시 받기",
    retryLabel: "다시 시도",
    appliedLabel: "적용되었습니다",
    failureGeneric: "지금은 제안을 가져올 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
    failureTimeout: "응답이 예상보다 오래 걸리고 있습니다. 다시 시도하거나 직접 답변을 계속 작성할 수 있습니다.",
    failureRateLimited: "AI 지원에 잠시 시간이 필요합니다. 곧 다시 시도하거나 직접 답변을 계속 작성할 수 있습니다.",
    failureUnavailable: "지금은 AI 지원을 사용할 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
    failureSafetyRefusal: "이 요청에 대한 제안을 제공할 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
  },
  errors: {
    projectNotFound: "프로젝트를 찾을 수 없습니다.",
    saveFailed: "마지막 변경사항을 저장하지 못했습니다. 다시 시도해 주세요.",
  },
};
