// Korean is the canonical source language — authored first, per
// sdd/context/01_product_vision.md#localization-principle. English (en.ts) is derived from
// this file to preserve meaning, not authored independently.

import type { Resources } from "./shape";

export const ko: Resources = {
  lifecycleStage: {
    captured: "시작 전",
    structuring: "구조화 중",
    scoped: "범위 설정됨",
    validating: "검증 중",
    validated: "검증됨",
    "build-ready": "빌드 준비 완료",
    archived: "보관됨",
  },
  common: {
    back: "이전",
    continue: "계속",
    cancel: "취소",
    create: "만들기",
    archive: "보관",
    edit: "수정",
    loading: "불러오는 중…",
    writeMyOwn: "직접 입력",
    yourAnswer: "답변",
    yourAnswerPlaceholder: "직접 답변을 입력하세요…",
    projectLabel: "프로젝트",
  },
  nav: {
    home: "홈",
    features: "기능",
    openWorkspace: "워크스페이스 열기",
    businessStructuring: "비즈니스 구조화",
    mvpPlanning: "MVP 계획",
    validationPlanning: "검증 계획",
    riskMemo: "리스크 메모",
    summary: "요약",
  },
  language: {
    korean: "한국어",
    english: "English",
  },
  landingVariants: {
    a: {
      // Problem Empathy — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "수동 워크스페이스 — V1은 AI 없이 동작해요",
      heroTitle: "아이디어는 있는데, 어디서부터 시작해야 할지 모르겠나요?",
      heroSubtitle: "Hypora는 막막한 아이디어를 구체적인 첫걸음으로 바꿔주는 구조화된 워크스페이스입니다.",
      ctaLabel: "첫걸음 시작하기",
      gapEyebrow: "이 사이 어딘가",
      gapTitle: "메모 앱도, 실행 도구도 채워주지 않는 자리가 있어요.",
      gapSupport: "많은 사람들이 바로 이 지점에서 조용히 멈춰요. 당신만 그런 게 아니에요.",
      gapNoteToolBody: "생각을 자유롭게 적을 수 있지만, 구조를 만들어주진 않아요.",
      gapExecToolBody: "이미 범위가 정해졌다고 가정하고, 관리만 도와줘요.",
      gapHyporaBody: "그 사이, 아이디어가 실행 가능한 계획이 되기 전 단계를 함께 채워줘요.",
      mechanismTitle: "혼자 고민하지 않아도 괜찮아요. 한 번에 하나씩, 편하게 답해보세요.",
      mechanismSupport: "미리 알아야 할 프레임워크는 없어요. 질문에 답하다 보면 자연스럽게 정리돼요.",
      mechanismPoint1: "한 번에 하나의 질문만 마주해요",
      mechanismPoint2: "제시된 선택지를 고르거나, 직접 적어도 좋아요",
      mechanismPoint3: "진행 상황은 언제나 보이고, 뒤로 가도 답은 그대로 남아요",
      svEyebrow: "정리하기 vs. 검증하기",
      svTitle: "정리도, 판단도 당신의 몫이에요 — 다만 혼자는 아니에요.",
      svSupport: "두 단계는 분명히 다르고, 순서대로 함께 걸어가요.",
      svStructuringLabel: "정리하기",
      svStructuringBody: "비즈니스 아이디어, 문제, 타겟 고객, 솔루션, 가치 제안 — 질문에 답하며 당신이 직접 정리해요.",
      svValidatingLabel: "검증하기",
      svValidatingBody: "가정 하나하나를 당신이 직접, 솔직하게 표시해요. 자동으로 확인되는 건 없어요.",
      svNote: "'검증됨'은 언제나 당신이 직접 표시한 것을 의미해요 — 자동 판단이나 외부 인증이 아니에요.",
      notTitle: "한 번에 하나의 아이디어를 위한 공간이에요. 떠올리는 도구들과는 조금 달라요.",
      notRow1Label: "메모 앱이 아니에요",
      notRow1Desc: "구조는 선택이 아니라 기본이에요. 그 구조 자체가 이 도구의 가치예요.",
      notRow2Label: "프로젝트 관리 도구가 아니에요",
      notRow2Desc: "실행 전 단계에서 멈춰요. 스프린트나 티켓은 다루지 않아요.",
      notRow3Label: "AI가 대신 써주는 도구가 아니에요",
      notRow3Desc: "V1에는 AI가 전혀 없어요. 나중에 생겨도 늘 제안만 할 뿐이에요.",
      notRow4Label: "아직 팀 도구는 아니에요",
      notRow4Desc: "지금은 한 사람, 한 아이디어에 깊이 집중하는 것에 맞춰져 있어요.",
      notScope: "이런 도구들과 헷갈리셨다면 당연해요. 하이포라는 의도적으로 다르게 만들어졌어요.",
      visionTitle: "지금 시작한 이 여정은, 앞으로도 계속 당신과 함께 자라요.",
      visionSupport:
        "오늘은 생각을 정리하는 걸 돕지만, 다음에는 그 계획을 실행으로 옮기는 것까지 함께해요 — 그래도 결정은 언제나 당신의 몫이에요.",
      visionThemes: [
        "아이디어가 진짜 무언가가 되도록",
        "생각을 정리한 뒤에도, 계속 곁에 남아서",
        "정리된 생각이 자신 있는 실행으로 이어지도록",
      ],
      closingTitle: "천천히, 한 걸음씩 시작해봐요.",
      closingLede: "질문 하나에 답하는 것부터 시작하면 돼요.",
      microCopy: "계정이 필요 없어요. 가입 절차도 없어요. 프로젝트는 이 브라우저에만, 오직 당신에게만 남아요.",
      secondaryLinkLabel: "아직 준비가 안 되셨다면? 하이포라의 방향을 먼저 살펴보기 →",
      featuresTitle: "시작을 위한 도구",
      featuresSubtitle: "막막했던 아이디어가 실행 가능한 계획이 되기까지.",
      featureProjectManagementDesc: "여러 아이디어 중 무엇부터 시작할지 고민된다면, 모두 한 곳에 정리하고 하나씩 살펴보세요.",
      featureBusinessStructuringDesc: "무엇을 먼저 정의해야 할지 모르겠다면, 다섯 가지 질문이 순서대로 안내합니다.",
      featureMvpPlanningDesc: "너무 많은 걸 한번에 만들려다 지쳤다면, 진짜 첫 버전의 경계를 함께 그려보세요.",
      featureValidationPlanningDesc: "확신이 없어 망설여진다면, 검증 가능한 질문으로 바꿔 답을 찾아보세요.",
      featureProjectSummaryDesc: "지금 어디까지 왔는지 헷갈린다면, 한눈에 준비 상태를 확인하세요.",
    },
    b: {
      // Loss Aversion — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "실행되지 않으면, 사라져요",
      heroTitle: "실행되지 않은 아이디어는 결국 사라집니다.",
      heroSubtitle: "머릿속에만 있는 아이디어는 잊혀지거나, 누군가 먼저 실행합니다. Hypora로 지금 구조화하세요.",
      ctaLabel: "아이디어 지키기",
      gapEyebrow: "놓치고 있는 지점",
      gapTitle: "메모는 정리해주지 않고, 실행 도구는 이미 늦은 뒤에야 쓸모 있어요.",
      gapSupport: "구조화되지 않은 채 남겨진 아이디어는 매일 조금씩 우선순위에서 밀려나요.",
      gapNoteToolBody: "자유롭게 적을 순 있지만, 방치되면 그대로 잊혀져요.",
      gapExecToolBody: "범위가 이미 정해졌다고 가정해요 — 정해지지 않았다면 소용없어요.",
      gapHyporaBody: "그 사이, 아이디어가 사라지기 전에 구조로 만들어요.",
      mechanismTitle: "질문 다섯 개면 충분해요. 더 늦기 전에 구조를 남기세요.",
      mechanismSupport: "프레임워크를 몰라도 괜찮아요. 지금 답하지 않으면, 이 생각은 다시 떠오르지 않을 수도 있어요.",
      mechanismPoint1: "한 번에 하나의 질문 — 미루지 않고 바로 답할 수 있어요",
      mechanismPoint2: "선택지를 고르거나 직접 입력 — 시간을 끌지 않아요",
      mechanismPoint3: "진행 상황이 남아요 — 지금까지의 생각을 잃지 않아요",
      svEyebrow: "구조화 vs. 검증",
      svTitle: "확인하지 않은 가정은, 나중에 더 큰 손실이 됩니다.",
      svSupport: "지금 검증하지 않으면, 잘못된 방향으로 이미 많은 시간을 쓴 뒤에야 알게 돼요.",
      svStructuringLabel: "구조화",
      svStructuringBody: "질문에 답하며 아이디어를 지금 정리하세요 — 미루면 흐려집니다.",
      svValidatingLabel: "검증",
      svValidatingBody: "가정을 하나씩 직접 확인하세요. 확인하지 않은 가정은 나중에 더 비싼 대가로 돌아옵니다.",
      svNote: "'검증됨'은 당신이 직접 확인했다는 뜻입니다 — 확인하지 않은 채 넘어가면, 나중에 그 대가를 치르게 됩니다.",
      notTitle: "다른 도구들이 놓치는 지점을 정확히 채웁니다.",
      notRow1Label: "메모 앱이 아닙니다",
      notRow1Desc: "적어두기만 하면, 결국 다시 보지 않게 되고 잊혀집니다.",
      notRow2Label: "프로젝트 관리 도구가 아닙니다",
      notRow2Desc: "범위가 정해지지 않은 채로는 관리할 것도 없습니다.",
      notRow3Label: "AI가 대신 써주는 도구가 아닙니다",
      notRow3Desc: "V1은 AI 없이 동작합니다 — 기다리다 시간을 잃지 마세요.",
      notRow4Label: "아직 팀 도구는 아닙니다",
      notRow4Desc: "지금은 한 사람의 아이디어를 먼저 지키는 데 집중합니다.",
      notScope: "다른 카테고리의 도구를 쓰고 있었다면, 바로 그 지점에서 아이디어를 잃고 있었을 수 있습니다.",
      visionTitle: "지금 붙잡은 구조는, 앞으로도 계속 당신 곁에 남습니다.",
      visionSupport:
        "오늘은 아이디어가 흐려지지 않게 돕지만, 다음에는 그 계획을 실행으로 이어가는 것까지 함께합니다 — 결정은 언제나 당신의 몫입니다.",
      visionThemes: [
        "아이디어가 끝까지 흐려지지 않도록",
        "정리한 생각이 실행까지 이어지도록",
        "당신의 성장과 함께 계속 자라도록",
      ],
      closingTitle: "더 늦기 전에, 지금 아이디어를 붙잡으세요.",
      closingLede: "구조화되지 않은 채 하루가 더 지나면, 그만큼 흐려집니다.",
      microCopy: "계정도, 가입도 필요 없습니다. 미루는 대신, 지금 바로 시작하세요.",
      secondaryLinkLabel: "그래도 아직 망설여진다면? 하이포라가 가는 방향을 먼저 확인해보세요 →",
      featuresTitle: "실행으로 이어지는 도구",
      featuresSubtitle: "아이디어가 사라지기 전에, 구조로 남기세요.",
      featureProjectManagementDesc: "여러 아이디어를 방치하지 마세요 — 모두 한 곳에서 관리하며 잊지 않도록 하세요.",
      featureBusinessStructuringDesc: "다섯 가지 질문에 답하는 순간부터, 아이디어는 더 이상 머릿속에만 머물지 않습니다.",
      featureMvpPlanningDesc: "범위를 정하지 않으면 실행은 계속 미뤄집니다 — 지금 첫 버전의 경계를 그으세요.",
      featureValidationPlanningDesc: "검증되지 않은 가정 위에 시간을 쓰기 전에, 먼저 확인하세요.",
      featureProjectSummaryDesc: "얼마나 진행되었는지 모른 채 방치하지 마세요 — 준비 상태를 항상 확인하세요.",
    },
    c: {
      // Execution Confidence — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "지금 실행을 시작하세요",
      heroTitle: "좋은 아이디어보다 좋은 실행이 이깁니다.",
      heroSubtitle: "Hypora는 아이디어를 실행 가능한 계획으로 바꾸는 구조화된 워크스페이스입니다 — 지금 실행을 시작하세요.",
      ctaLabel: "실행 시작하기",
      gapEyebrow: "그 차이",
      gapTitle: "생각만 하는 사람과 실행하는 사람의 차이는, 구조뿐입니다.",
      gapSupport: "메모 도구는 정리해주지 않고, 실행 도구는 이미 정해진 범위를 관리할 뿐이에요. 그 사이를 채우는 것이 실행의 시작이에요.",
      gapNoteToolBody: "자유롭게 적을 수 있지만, 실행으로 이어지진 않아요.",
      gapExecToolBody: "이미 범위가 정해졌다고 가정해요.",
      gapHyporaBody: "구조를 실행 가능한 계획으로 바꿔요 — 지금 시작할 수 있게.",
      mechanismTitle: "질문에 답하는 순간, 계획은 실행 가능한 형태로 바뀝니다.",
      mechanismSupport: "프레임워크를 몰라도 됩니다. 답하는 만큼 곧바로 구조가 됩니다.",
      mechanismPoint1: "하나의 질문에 집중 — 바로 다음 걸음으로 이어져요",
      mechanismPoint2: "선택하거나 직접 입력 — 속도를 늦추지 않아요",
      mechanismPoint3: "진행 상황이 쌓여요 — 멈췄던 지점부터 다시 실행해요",
      svEyebrow: "구조화 vs. 검증",
      svTitle: "구조화는 출발선, 검증은 실행으로 가는 다음 걸음입니다.",
      svSupport: "둘 다 당신이 직접 하지만, 각각의 역할은 분명해요.",
      svStructuringLabel: "구조화",
      svStructuringBody: "질문에 답하며 계획을 세워요 — 실행을 위한 첫 걸음이에요.",
      svValidatingLabel: "검증",
      svValidatingBody: "가정을 하나씩 직접 확인하며, 실행할 준비가 됐는지 판단해요.",
      svNote: "'검증됨'은 당신이 실행해도 좋다고 직접 판단했다는 뜻이에요.",
      notTitle: "진짜 실행을 원한다면, 이 도구들과는 다른 선택이 필요합니다.",
      notRow1Label: "메모 앱이 아닙니다",
      notRow1Desc: "적기만 해서는 실행으로 이어지지 않아요.",
      notRow2Label: "프로젝트 관리 도구가 아닙니다",
      notRow2Desc: "범위가 정해지기 전 단계에서 멈춰요 — 실행 관리는 그다음이에요.",
      notRow3Label: "AI가 대신 써주는 도구가 아닙니다",
      notRow3Desc: "V1은 AI 없이 동작해요. AI는 나중에도 제안만 해요 — 실행의 주도권은 당신에게 있어요.",
      notRow4Label: "아직 팀 도구는 아닙니다",
      notRow4Desc: "지금은 한 사람이 빠르게 실행 가능한 계획을 세우는 데 집중해요.",
      notScope: "생각만 하고 멈춰있는 도구가 아니라, 실행으로 이어지는 구조를 원한다면 여기서 시작하세요.",
      visionTitle: "구조화에서 자신 있는 실행까지, 하이포라는 그 여정 내내 함께합니다.",
      visionSupport:
        "오늘은 계획을 세우는 걸 돕지만, 다음에는 그 계획을 실행하는 것까지 돕게 됩니다 — 방향은 언제나 당신이 정합니다.",
      visionThemes: [
        "생각이 실행 가능한 계획이 되도록",
        "계획이 자신 있는 실행으로 이어지도록",
        "실행의 매 단계마다 함께 성장하도록",
      ],
      closingTitle: "지금, 실행을 시작하세요.",
      closingLede: "질문에 답하는 순간부터 계획은 움직이기 시작합니다.",
      microCopy: "계정도 가입도 필요 없어요. 지금 바로 첫 질문에 답해보세요.",
      secondaryLinkLabel: "먼저 하이포라의 방향을 보고 싶다면? →",
      featuresTitle: "실행을 위한 도구",
      featuresSubtitle: "아이디어에서 실행까지, 필요한 모든 것.",
      featureProjectManagementDesc: "실행 중인 모든 아이디어를 하나의 대시보드에서 관리하세요.",
      featureBusinessStructuringDesc: "다섯 가지 질문으로 아이디어를 실행 가능한 형태로 구조화하세요.",
      featureMvpPlanningDesc: "범위를 정하고, 우선순위대로 실행하세요.",
      featureValidationPlanningDesc: "가정을 검증 가능한 항목으로 바꿔 확인하며 실행하세요.",
      featureProjectSummaryDesc: "실행 준비 상태를 한눈에 확인하세요.",
    },
  },
  landing: {
    footer: "Hypora — 만들기 전에 아이디어를 구조화하세요.",
    featuresTitle: "기능",
    featuresSubtitle: "아이디어에서 검증된 계획까지 필요한 모든 것.",
    featureProjectManagementName: "프로젝트 관리",
    featureProjectManagementDesc: "구조화 중인 모든 비즈니스 아이디어를 하나의 대시보드에서 만들고 관리하세요.",
    featureBusinessStructuringName: "비즈니스 구조화",
    featureBusinessStructuringDesc: "5개 항목의 캔버스 — 비즈니스 아이디어, 문제, 타겟 고객, 솔루션, 가치 제안.",
    featureMvpPlanningName: "MVP 계획",
    featureMvpPlanningDesc: "범위 경계를 정하고 첫 버전을 구성할 기능의 우선순위를 정하세요.",
    featureValidationPlanningName: "검증 계획",
    featureValidationPlanningDesc: "가설을 테스트 가능한 가정으로 바꾸고, 각각에 방법과 성공 기준을 부여하세요.",
    featureProjectSummaryName: "프로젝트 요약",
    featureProjectSummaryDesc: "한눈에 준비 상태를 확인하고, 계획이 빌드 준비 완료되었을 때 확정하세요.",
    gapNoteToolTag: "메모 도구",
    gapExecToolTag: "실행 도구",
    gapHyporaTag: "하이포라",
    mechanismQuestionLabel: "질문 3 / 5",
    mechanismQuestionText: "이 아이디어는 누구를 위한 건가요?",
    mechanismChip1: "바쁜 직장인",
    mechanismChip2: "초기 창업가",
    mechanismChip3: "소규모 팀",
    mechanismChip4: "직접 입력하기",
    mechanismResultLabel: "캔버스에 저장됨 → 타겟 고객 ✓",
    svCheckOpenLabel: "“고객이 이 문제에 돈을 지불할 것이다” — 아직 가정",
    svCheckDoneLabel: "“이 문제는 실제로 존재한다” — 직접 검증함",
    mechanismEyebrow: "하이포라가 생각하는 방식",
    notEyebrow: "하이포라는",
    visionEyebrow: "하이포라의 방향",
  },
  dashboard: {
    title: "내 프로젝트",
    subtitle: "구조화 중인 모든 비즈니스 아이디어를 한곳에서.",
    newProject: "새 프로젝트",
    projectNameLabel: "프로젝트 이름",
    projectNamePlaceholder: "예: 동네 도구 대여 앱",
    emptyTitle: "아직 프로젝트가 없습니다",
    emptyDescription: "첫 프로젝트를 만들어 아이디어 구조화를 시작하세요.",
    open: "열기",
    showArchived: "보관된 프로젝트 보기",
    hideArchived: "보관된 프로젝트 숨기기",
    archiveConfirmTitle: "이 프로젝트를 보관하시겠습니까?",
    archiveConfirmDescription:
      "기본 목록에서 숨겨지지만 삭제되지는 않습니다 — 언제든지 보관된 프로젝트를 다시 볼 수 있습니다.",
    loadingProjects: "프로젝트를 불러오는 중…",
  },
  businessStructuring: {
    title: "비즈니스 구조화",
    subtitle: "한 번에 하나의 질문에 집중하세요.",
    progressLabel: (current, total) => `${total}개 중 ${current}번째 질문`,
    continueToReview: "검토로 이동",
    reviewTitle: "비즈니스 캔버스 검토",
    reviewSubtitle: "모든 내용을 한곳에서 — 확정하기 전에 무엇이든 수정하세요.",
    riskNotesLabel: "리스크 메모 (선택)",
    riskNotesHint: "이 아이디어가 실패할 수 있는 이유는 무엇인가요? 완료를 막지 않으며, 스스로의 성찰을 위한 것입니다.",
    confirmAndContinue: "확인하고 MVP 계획으로 이동",
    loadingProject: "프로젝트를 불러오는 중…",
    guardedNotice: "먼저 비즈니스 구조화와 MVP 계획을 완료하세요 — MVP 범위와 기능 계획이 모두 완료되면 검증 계획을 사용할 수 있습니다.",
  },
  riskMemo: {
    title: "리스크 메모",
    subtitle: "기술적 리스크, 비즈니스 리스크, 그리고 아직 알지 못하는 것들을 기록하세요. 모든 항목은 선택 사항입니다.",
    technicalRisksLabel: "기술적 리스크",
    businessRisksLabel: "비즈니스 리스크",
    openQuestionsLabel: "아직 모르는 것",
  },
  question: {
    businessIdea: {
      title: "아이디어를 한두 문장으로 설명해 주세요.",
      presets: [
        "[대상]이 [일]을 더 쉽게 할 수 있도록 돕는 구독 서비스.",
        "[그룹 A]와 [그룹 B]를 연결하는 마켓플레이스.",
        "[대상]을 위해 [번거로운 작업]을 자동화하는 도구.",
        "[원하는 것]을 [대상]에게 더 가까이 가져다주는 지역 서비스.",
      ],
    },
    problem: {
      title: "어떤 문제를 해결하려고 하나요? 누구의 문제인가요?",
      presets: [
        "[X]를 쉽게 할 방법이 없어서 사람들이 시간이나 돈을 낭비하고 있습니다.",
        "기존 옵션은 [대상]에게 너무 비싸거나, 느리거나, 불편합니다.",
        "[대상]이 오늘날 [X]를 찾거나 할 수 있는 신뢰할 수 있는 방법이 없습니다.",
      ],
    },
    targetCustomer: {
      title: "구체적으로 누가 이 문제를 겪고 있나요?",
      presets: ["바쁜 도시 직장인", "소상공인", "어린 자녀를 둔 부모", "학생", "새로운 동네나 도시로 이사한 사람"],
    },
    solution: {
      title: "무엇을 만들려고 하나요?",
      presets: [
        "[대상]을 [자원]과 직접 연결하는 모바일 앱.",
        "[수동 프로세스]를 자동화하는 간단한 웹 도구.",
        "신뢰·안전 기능이 내장된 큐레이션 마켓플레이스.",
      ],
    },
    valueProposition: {
      title: "사람들이 다른 대안 대신 이것을 선택하는 이유는 무엇인가요?",
      presets: [
        "기존 대안보다 시간을 절약해 줍니다.",
        "기존 옵션보다 비용이 적게 듭니다.",
        "다른 어떤 것도 하지 못하는 방식으로 신뢰와 커뮤니티를 만듭니다.",
        "경쟁자가 제공하지 못하는 때와 장소에서 이용할 수 있어 더 편리합니다.",
      ],
    },
  },
  mvpPlanning: {
    title: "MVP 계획",
    subtitle: "가장 작은 가치 있는 버전과 이를 만드는 데 필요한 것을 정의하세요.",
    scopeLabel: "MVP 범위",
    scopeHint: "첫 버전에 무엇이 포함되나요? 명시적으로 제외되는 것은 무엇인가요?",
    markScopeComplete: "범위 완료 표시",
    markedComplete: "완료 표시됨 ✓",
    featurePlanningTitle: "기능 계획",
    addFeatureLabel: "기능 추가",
    addFeaturePlaceholder: "예: 카테고리별 검색",
    add: "추가",
    remove: "제거",
    emptyFeaturesTitle: "아직 계획된 기능이 없습니다",
    emptyFeaturesDescription: "위에서 첫 번째 기능을 추가하세요.",
    markFeaturePlanningComplete: "기능 계획 완료 표시",
    priorityMust: "필수",
    priorityShould: "권장",
    priorityCould: "선택",
    inScope: "범위 포함",
    outOfScope: "범위 제외",
    readyForValidation: "검증 계획 준비 완료",
    suggestFeaturesLabel: "기능 제안받기",
    suggestedFeaturesTitle: "제안된 기능",
    suggestedFeaturesEmptyNotice: "지금은 새로운 제안이 없습니다.",
    duplicateIndicator: "이미 계획에 있음",
    featuresAddedLabel: (count) => `기능 ${count}개 추가됨`,
    historyToggleLabel: "히스토리",
    historyTitle: "기능 히스토리",
    historyEmptyDescription: "아직 기록된 기능 변경 사항이 없습니다.",
    historyCreatedLabel: "추가됨",
    historyRemovedLabel: "제거됨",
    historyAnnotationPlaceholder: "선택적으로 메모를 추가하세요…",
  },
  validationPlanning: {
    title: "검증 계획",
    subtitle: "가설을 테스트 가능한 가정으로 바꾸세요.",
    reopenMvpPlanning: "MVP 계획 다시 열기",
    addAssumptionLabel: "가정 추가",
    addAssumptionPlaceholder: "예: 고객이 이 서비스에 월 1만원을 지불할 것이다",
    add: "추가",
    emptyTitle: "아직 가정이 없습니다",
    emptyDescription: "최소 하나의 가정을 추가하세요 — 빈 체크리스트는 검증 완료로 표시할 수 없습니다.",
    methodLabel: "검증 방법",
    methodPlaceholder: "이것을 어떻게 확인할 건가요?",
    criterionLabel: "성공 기준",
    criterionPlaceholder: "어떤 결과가 나오면 확인된 것으로 볼 건가요?",
    statusOpen: "미해결",
    statusValidated: "검증됨",
    statusInvalidated: "반증됨",
    markValidated: "검증됨으로 표시",
    markInvalidated: "반증됨으로 표시",
    notReadyNotice: "먼저 비즈니스 구조화와 MVP 계획을 완료하세요 — MVP 범위와 기능 계획이 모두 완료되면 검증 계획을 사용할 수 있습니다.",
    allResolvedNotice: "모든 가정이 해결되었습니다 — 빌드 준비 확정을 위해 요약을 확인하세요",
  },
  projectSummary: {
    title: "프로젝트 요약",
    subtitle: "모든 항목에서 종합한, 한눈에 보는 준비 상태.",
    businessCanvasTitle: "비즈니스 캔버스",
    fieldsCompleted: (done, total) => `${total}개 중 ${done}개 항목 완료`,
    mvpPlanningTitle: "MVP 계획",
    mvpPlanningStatus: (scopeComplete, featureCount, planningComplete) =>
      `범위 ${scopeComplete ? "완료" : "진행 중"} · 기능 ${featureCount}개 계획됨, 기능 계획 ${planningComplete ? "완료" : "진행 중"}`,
    validationPlanningTitle: "검증 계획",
    validationStatus: (resolved, total) => `${total}개 중 ${resolved}개 가정 해결됨`,
    confirmBuildReady: "빌드 준비 완료 확정",
    isBuildReady: "이 프로젝트는 빌드 준비가 완료되었습니다",
    blockingCanvas: "계속하려면 비즈니스 캔버스의 5개 항목을 모두 완료하세요.",
    blockingScope: "MVP 범위를 완료로 표시하세요.",
    blockingFeaturePlanning: "기능 계획을 완료로 표시하세요.",
    blockingValidationEmpty: "검증 체크리스트에 최소 하나의 가정을 추가하세요.",
    blockingValidationOpen: "모든 미해결 검증 체크리스트 항목을 해결하세요.",
    blockingConfirm: "실행할 준비가 되면 이 프로젝트를 빌드 준비 완료로 확정하세요.",
    goToCanvas: "비즈니스 캔버스로 이동",
    goToMvpPlanning: "MVP 계획으로 이동",
    goToValidationPlanning: "검증 계획으로 이동",
    summaryCardTitle: "요약",
    summaryNotGenerated: "비즈니스 캔버스가 완료되면 요약이 자동으로 생성됩니다.",
    summaryGenerating: "프로젝트 요약을 생성하는 중입니다…",
    summaryOutOfSyncBadge: "동기화 필요",
    summaryOutOfSyncNotice: "이 요약은 최근 변경 사항이 반영되기 전에 작성되었습니다. 동기화하기 전까지는 아래 내용이 그대로 표시됩니다.",
    syncSummaryButton: "요약 동기화",
    syncDialogTitle: "요약 동기화",
    syncDialogAsIsLabel: "현재 저장된 요약 (As-Is)",
    syncDialogToBeLabel: "새 초안 (To-Be)",
    syncDialogToBeEmptyHint: "\"AI 요약 업데이트\"를 눌러 새 요약 초안을 생성한 뒤 자유롭게 수정할 수 있습니다.",
    aiSummaryUpdateButton: "AI 요약 업데이트",
    applyButton: "적용",
  },
  aiAssistant: {
    askAiLabel: "AI에게 제안 받기",
    aiTag: "AI",
    loadingLabel: "제안을 가져오는 중…",
    acceptLabel: "적용",
    rejectLabel: "닫기",
    regenerateLabel: "다시 받기",
    retryLabel: "다시 시도",
    appliedLabel: "적용되었습니다",
    failureGeneric: "지금은 제안을 가져올 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
    failureTimeout: "응답이 예상보다 오래 걸리고 있습니다. 다시 시도하거나 직접 답변을 계속 작성할 수 있습니다.",
    failureRateLimited: "AI 지원에 잠시 시간이 필요합니다. 곧 다시 시도하거나 직접 답변을 계속 작성할 수 있습니다.",
    failureUnavailable: "지금은 AI 지원을 사용할 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
    failureSafetyRefusal: "이 요청에 대한 제안을 제공할 수 없습니다. 직접 답변을 계속 작성할 수 있습니다.",
  },
  errors: {
    projectNotFound: "프로젝트를 찾을 수 없습니다.",
    saveFailed: "마지막 변경사항을 저장하지 못했습니다. 다시 시도해 주세요.",
  },
};
