// Korean is the canonical source language — authored first, per
// sdd/context/01_product_vision.md#localization-principle. English (en.ts) is derived from
// this file to preserve meaning, not authored independently.
//
// Terminology per Hypora UX Terminology Strategy V1-V3 (2026-07-20): plain, evidence-based,
// non-jargon language for first-time users with no startup/business background.

import type { Resources } from "./shape";

export const ko: Resources = {
  lifecycleStage: {
    captured: "시작 전",
    structuring: "아이디어 설명 중",
    scoped: "첫 버전 계획 중",
    validating: "테스트 중",
    validated: "테스트 완료",
    "build-ready": "계획 완료",
    archived: "보관됨",
  },
  common: {
    back: "이전",
    continue: "계속",
    cancel: "취소",
    create: "만들기",
    archive: "보관",
    edit: "수정",
    loading: "불러오는 중…",
    writeMyOwn: "직접 입력",
    yourAnswer: "답변",
    yourAnswerPlaceholder: "직접 답변을 입력하세요…",
    projectLabel: "프로젝트",
  },
  nav: {
    home: "홈",
    features: "기능",
    openWorkspace: "워크스페이스 열기",
    businessStructuring: "아이디어",
    mvpPlanning: "첫 버전",
    validationPlanning: "테스트",
    riskMemo: "리스크",
    summary: "개요",
  },
  language: {
    korean: "한국어",
    english: "English",
  },
  landingVariants: {
    a: {
      // Problem Empathy — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "시작하는 데 AI가 필요 없어요",
      heroTitle: "아이디어는 있는데, 어디서부터 시작해야 할지 모르겠나요?",
      heroSubtitle: "Hypora는 막막한 아이디어를 구체적인 첫걸음으로 바꿔주는 구조화된 워크스페이스입니다.",
      ctaLabel: "첫걸음 시작하기",
      gapEyebrow: "이 사이 어딘가",
      gapTitle: "메모 앱도, 실행 도구도 채워주지 않는 자리가 있어요.",
      gapSupport: "많은 사람들이 바로 이 지점에서 조용히 멈춰요. 당신만 그런 게 아니에요.",
      gapNoteToolBody: "생각을 자유롭게 적을 수 있지만, 구조를 만들어주진 않아요.",
      gapExecToolBody: "이미 범위가 정해졌다고 가정하고, 관리만 도와줘요.",
      gapHyporaBody: "그 사이, 아이디어가 실행 가능한 계획이 되기 전 단계를 함께 채워줘요.",
      mechanismTitle: "혼자 고민하지 않아도 괜찮아요. 한 번에 하나씩, 편하게 답해보세요.",
      mechanismSupport: "미리 알아야 할 프레임워크는 없어요. 질문에 답하다 보면 자연스럽게 정리돼요.",
      mechanismPoint1: "한 번에 하나의 질문만 마주해요",
      mechanismPoint2: "제시된 선택지를 고르거나, 직접 적어도 좋아요",
      mechanismPoint3: "진행 상황은 언제나 보이고, 뒤로 가도 답은 그대로 남아요",
      svEyebrow: "정리하기 vs. 테스트하기",
      svTitle: "정리도, 판단도 당신의 몫이에요 — 다만 혼자는 아니에요.",
      svSupport: "두 단계는 분명히 다르고, 순서대로 함께 걸어가요.",
      svStructuringLabel: "정리하기",
      svStructuringBody: "비즈니스 아이디어, 문제, 타겟 고객, 솔루션, 가치 제안 — 질문에 답하며 당신이 직접 정리해요.",
      svValidatingLabel: "테스트하기",
      svValidatingBody: "당신이 믿는 것을, 직접, 솔직하게 확인해요. 자동으로 결정되는 건 없어요.",
      svNote: "'뒷받침됨'은 언제나 당신이 직접 판단한 것을 의미해요 — 자동 판단이나 외부 인증이 아니에요.",
      notTitle: "한 번에 하나의 아이디어를 위한 공간이에요. 떠올리는 도구들과는 조금 달라요.",
      notRow1Label: "메모 앱이 아니에요",
      notRow1Desc: "구조는 선택이 아니라 기본이에요. 그 구조 자체가 이 도구의 가치예요.",
      notRow2Label: "프로젝트 관리 도구가 아니에요",
      notRow2Desc: "실행 전 단계에서 멈춰요. 스프린트나 티켓은 다루지 않아요.",
      notRow3Label: "AI가 대신 써주는 도구가 아니에요",
      notRow3Desc: "지금은 AI가 없어요. 나중에 생겨도 늘 제안만 하고, 대신 결정하진 않아요.",
      notRow4Label: "아직 팀 도구는 아니에요",
      notRow4Desc: "지금은 한 사람, 한 아이디어에 깊이 집중하는 것에 맞춰져 있어요.",
      notScope: "이런 도구들과 헷갈리셨다면 당연해요. 하이포라는 의도적으로 다르게 만들어졌어요.",
      visionTitle: "지금 시작한 이 여정은, 앞으로도 계속 당신과 함께 자라요.",
      visionSupport:
        "오늘은 생각을 정리하는 걸 돕지만, 다음에는 그 계획을 실행으로 옮기는 것까지 함께해요 — 그래도 결정은 언제나 당신의 몫이에요.",
      visionThemes: [
        "아이디어가 진짜 무언가가 되도록",
        "생각을 정리한 뒤에도, 계속 곁에 남아서",
        "정리된 생각이 자신 있는 실행으로 이어지도록",
      ],
      closingTitle: "천천히, 한 걸음씩 시작해봐요.",
      closingLede: "질문 하나에 답하는 것부터 시작하면 돼요.",
      microCopy: "계정이 필요 없어요. 가입 절차도 없어요. 프로젝트는 이 브라우저에만, 오직 당신에게만 남아요.",
      secondaryLinkLabel: "아직 준비가 안 되셨다면? 하이포라의 방향을 먼저 살펴보기 →",
      featuresTitle: "시작을 위한 도구",
      featuresSubtitle: "막막했던 아이디어가 실행 가능한 계획이 되기까지.",
      featureProjectManagementDesc: "여러 아이디어 중 무엇부터 시작할지 고민된다면, 모두 한 곳에 정리하고 하나씩 살펴보세요.",
      featureBusinessStructuringDesc: "무엇을 먼저 정의해야 할지 모르겠다면, 다섯 가지 질문이 순서대로 안내합니다.",
      featureMvpPlanningDesc: "너무 많은 걸 한번에 만들려다 지쳤다면, 진짜 첫 버전의 경계를 함께 그려보세요.",
      featureValidationPlanningDesc: "확신이 없어 망설여진다면, 테스트 가능한 질문으로 바꿔 답을 찾아보세요.",
      featureProjectSummaryDesc: "지금 어디까지 왔는지 헷갈린다면, 한눈에 준비 상태를 확인하세요.",
    },
    b: {
      // Loss Aversion — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "끝내지 않으면, 사라져요",
      heroTitle: "실행되지 않은 아이디어는 결국 사라집니다.",
      heroSubtitle: "머릿속에만 있는 아이디어는 잊혀지거나, 누군가 먼저 실행합니다. Hypora로 지금 구조화하세요.",
      ctaLabel: "아이디어 지키기",
      gapEyebrow: "놓치고 있는 지점",
      gapTitle: "메모는 정리해주지 않고, 실행 도구는 이미 늦은 뒤에야 쓸모 있어요.",
      gapSupport: "구조화되지 않은 채 남겨진 아이디어는 매일 조금씩 우선순위에서 밀려나요.",
      gapNoteToolBody: "자유롭게 적을 순 있지만, 방치되면 그대로 잊혀져요.",
      gapExecToolBody: "범위가 이미 정해졌다고 가정해요 — 정해지지 않았다면 소용없어요.",
      gapHyporaBody: "그 사이, 아이디어가 사라지기 전에 구조로 만들어요.",
      mechanismTitle: "질문 다섯 개면 충분해요. 더 늦기 전에 구조를 남기세요.",
      mechanismSupport: "프레임워크를 몰라도 괜찮아요. 지금 답하지 않으면, 이 생각은 다시 떠오르지 않을 수도 있어요.",
      mechanismPoint1: "한 번에 하나의 질문 — 미루지 않고 바로 답할 수 있어요",
      mechanismPoint2: "선택지를 고르거나 직접 입력 — 시간을 끌지 않아요",
      mechanismPoint3: "진행 상황이 남아요 — 지금까지의 생각을 잃지 않아요",
      svEyebrow: "정리 vs. 테스트",
      svTitle: "확인하지 않은 생각은, 나중에 더 큰 손실이 됩니다.",
      svSupport: "지금 테스트하지 않으면, 잘못된 방향으로 이미 많은 시간을 쓴 뒤에야 알게 돼요.",
      svStructuringLabel: "정리",
      svStructuringBody: "질문에 답하며 아이디어를 지금 정리하세요 — 미루면 흐려집니다.",
      svValidatingLabel: "테스트",
      svValidatingBody: "당신이 믿는 것을, 대가를 치르기 전에 확인하세요.",
      svNote: "'뒷받침됨'은 당신이 직접 확인했다는 뜻입니다 — 확인하지 않은 채 넘어가면, 나중에 그 대가를 치르게 됩니다.",
      notTitle: "다른 도구들이 놓치는 지점을 정확히 채웁니다.",
      notRow1Label: "메모 앱이 아닙니다",
      notRow1Desc: "적어두기만 하면, 결국 다시 보지 않게 되고 잊혀집니다.",
      notRow2Label: "프로젝트 관리 도구가 아닙니다",
      notRow2Desc: "범위가 정해지지 않은 채로는 관리할 것도 없습니다.",
      notRow3Label: "AI가 대신 써주는 도구가 아닙니다",
      notRow3Desc: "아직 AI가 없습니다 — 기다리다 시간을 잃지 마세요.",
      notRow4Label: "아직 팀 도구는 아닙니다",
      notRow4Desc: "지금은 한 사람의 아이디어를 먼저 지키는 데 집중합니다.",
      notScope: "다른 카테고리의 도구를 쓰고 있었다면, 바로 그 지점에서 아이디어를 잃고 있었을 수 있습니다.",
      visionTitle: "지금 붙잡은 구조는, 앞으로도 계속 당신 곁에 남습니다.",
      visionSupport:
        "오늘은 아이디어가 흐려지지 않게 돕지만, 다음에는 그 계획을 실행으로 이어가는 것까지 함께합니다 — 결정은 언제나 당신의 몫입니다.",
      visionThemes: [
        "아이디어가 끝까지 흐려지지 않도록",
        "정리한 생각이 실행까지 이어지도록",
        "당신의 성장과 함께 계속 자라도록",
      ],
      closingTitle: "더 늦기 전에, 지금 아이디어를 붙잡으세요.",
      closingLede: "구조화되지 않은 채 하루가 더 지나면, 그만큼 흐려집니다.",
      microCopy: "계정도, 가입도 필요 없습니다. 미루는 대신, 지금 바로 시작하세요.",
      secondaryLinkLabel: "그래도 아직 망설여진다면? 하이포라가 가는 방향을 먼저 확인해보세요 →",
      featuresTitle: "실행으로 이어지는 도구",
      featuresSubtitle: "아이디어가 사라지기 전에, 구조로 남기세요.",
      featureProjectManagementDesc: "여러 아이디어를 방치하지 마세요 — 모두 한 곳에서 관리하며 잊지 않도록 하세요.",
      featureBusinessStructuringDesc: "다섯 가지 질문에 답하는 순간부터, 아이디어는 더 이상 머릿속에만 머물지 않습니다.",
      featureMvpPlanningDesc: "무엇을 먼저 만들지 정하지 않으면 계속 미뤄집니다 — 지금 그 경계를 그으세요.",
      featureValidationPlanningDesc: "확인되지 않은 생각 위에 시간을 쓰기 전에, 먼저 확인하세요.",
      featureProjectSummaryDesc: "얼마나 진행되었는지 모른 채 방치하지 마세요 — 준비 상태를 항상 확인하세요.",
    },
    c: {
      // Execution Confidence — per sdd/context/07_landing_experiment_strategy.md
      heroEyebrow: "지금 실행을 시작하세요",
      heroTitle: "좋은 아이디어보다 좋은 실행이 이깁니다.",
      heroSubtitle: "Hypora는 아이디어를 실행 가능한 계획으로 바꾸는 구조화된 워크스페이스입니다 — 지금 실행을 시작하세요.",
      ctaLabel: "실행 시작하기",
      gapEyebrow: "그 차이",
      gapTitle: "생각만 하는 사람과 실행하는 사람의 차이는, 구조뿐입니다.",
      gapSupport: "메모 도구는 정리해주지 않고, 실행 도구는 이미 정해진 범위를 관리할 뿐이에요. 그 사이를 채우는 것이 실행의 시작이에요.",
      gapNoteToolBody: "자유롭게 적을 수 있지만, 실행으로 이어지진 않아요.",
      gapExecToolBody: "이미 범위가 정해졌다고 가정해요.",
      gapHyporaBody: "구조를 실행 가능한 계획으로 바꿔요 — 지금 시작할 수 있게.",
      mechanismTitle: "질문에 답하는 순간, 계획은 실행 가능한 형태로 바뀝니다.",
      mechanismSupport: "프레임워크를 몰라도 됩니다. 답하는 만큼 곧바로 구조가 됩니다.",
      mechanismPoint1: "하나의 질문에 집중 — 바로 다음 걸음으로 이어져요",
      mechanismPoint2: "선택하거나 직접 입력 — 속도를 늦추지 않아요",
      mechanismPoint3: "진행 상황이 쌓여요 — 멈췄던 지점부터 다시 실행해요",
      svEyebrow: "정리 vs. 테스트",
      svTitle: "정리는 출발선, 테스트는 실행으로 가는 다음 걸음입니다.",
      svSupport: "둘 다 당신이 직접 하지만, 각각의 역할은 분명해요.",
      svStructuringLabel: "정리",
      svStructuringBody: "질문에 답하며 계획을 세워요 — 실행을 위한 첫 걸음이에요.",
      svValidatingLabel: "테스트",
      svValidatingBody: "당신이 믿는 것을 하나씩 확인하며, 계획이 완성됐는지 판단해요.",
      svNote: "'뒷받침됨'은 당신이 실행해도 좋다고 직접 판단했다는 뜻이에요.",
      notTitle: "진짜 실행을 원한다면, 이 도구들과는 다른 선택이 필요합니다.",
      notRow1Label: "메모 앱이 아닙니다",
      notRow1Desc: "적기만 해서는 실행으로 이어지지 않아요.",
      notRow2Label: "프로젝트 관리 도구가 아닙니다",
      notRow2Desc: "범위가 정해지기 전 단계에서 멈춰요 — 실행 관리는 그다음이에요.",
      notRow3Label: "AI가 대신 써주는 도구가 아닙니다",
      notRow3Desc: "지금은 AI가 없어요. AI는 나중에도 제안만 해요 — 실행의 주도권은 당신에게 있어요.",
      notRow4Label: "아직 팀 도구는 아닙니다",
      notRow4Desc: "지금은 한 사람이 빠르게 실행 가능한 계획을 세우는 데 집중해요.",
      notScope: "생각만 하고 멈춰있는 도구가 아니라, 실행으로 이어지는 구조를 원한다면 여기서 시작하세요.",
      visionTitle: "구조화에서 자신 있는 실행까지, 하이포라는 그 여정 내내 함께합니다.",
      visionSupport:
        "오늘은 계획을 세우는 걸 돕지만, 다음에는 그 계획을 실행하는 것까지 돕게 됩니다 — 방향은 언제나 당신이 정합니다.",
      visionThemes: [
        "생각이 실행 가능한 계획이 되도록",
        "계획이 자신 있는 실행으로 이어지도록",
        "실행의 매 단계마다 함께 성장하도록",
      ],
      closingTitle: "지금, 실행을 시작하세요.",
      closingLede: "질문에 답하는 순간부터 계획은 움직이기 시작합니다.",
      microCopy: "계정도 가입도 필요 없어요. 지금 바로 첫 질문에 답해보세요.",
      secondaryLinkLabel: "먼저 하이포라의 방향을 보고 싶다면? →",
      featuresTitle: "실행을 위한 도구",
      featuresSubtitle: "아이디어에서 실행까지, 필요한 모든 것.",
      featureProjectManagementDesc: "실행 중인 모든 아이디어를 하나의 대시보드에서 관리하세요.",
      featureBusinessStructuringDesc: "다섯 가지 질문으로 아이디어를 실제로 만들 수 있는 형태로 바꿔보세요.",
      featureMvpPlanningDesc: "무엇을 먼저 만들지 정하고, 우선순위대로 실행하세요.",
      featureValidationPlanningDesc: "당신이 믿는 것을 테스트로 바꾸고, 확인한 뒤 실행하세요.",
      featureProjectSummaryDesc: "실행 준비 상태를 한눈에 확인하세요.",
    },
  },
  landing: {
    footer: "Hypora — 만들기 전에 아이디어를 정리하세요.",
    featuresTitle: "기능",
    featuresSubtitle: "아이디어에서 테스트를 마친 계획까지 필요한 모든 것.",
    featureProjectManagementName: "프로젝트 관리",
    featureProjectManagementDesc: "지금 진행 중인 모든 아이디어를 하나의 대시보드에서 만들고 관리하세요.",
    featureBusinessStructuringName: "아이디어 설명하기",
    featureBusinessStructuringDesc: "아이디어에 대한 다섯 가지 질문 — 무엇인지, 어떤 문제인지, 누구를 위한 것인지, 무엇을 만들지, 왜 더 나은지.",
    featureMvpPlanningName: "첫 버전 계획하기",
    featureMvpPlanningDesc: "무엇을 먼저 만들지 정하고, 가장 중요한 기능부터 우선순위를 매기세요.",
    featureValidationPlanningName: "아이디어 테스트하기",
    featureValidationPlanningDesc: "당신이 믿는 것을 테스트할 수 있는 항목으로 바꾸세요. 각 항목에 확인 방법과 무엇을 보면 알 수 있는지를 함께 적어요.",
    featureProjectSummaryName: "개요",
    featureProjectSummaryDesc: "얼마나 진행됐는지 한눈에 확인하고, 계획이 완성되면 확정하세요.",
    gapNoteToolTag: "메모 도구",
    gapExecToolTag: "프로젝트 도구",
    gapHyporaTag: "하이포라",
    mechanismQuestionLabel: "질문 3 / 5",
    mechanismQuestionText: "이 아이디어는 누구를 위한 건가요?",
    mechanismChip1: "바쁜 직장인",
    mechanismChip2: "초기 창업가",
    mechanismChip3: "소규모 팀",
    mechanismChip4: "직접 입력하기",
    mechanismResultLabel: "아이디어에 저장됨 → 누구를 위한 것인지 ✓",
    svCheckOpenLabel: "“고객이 이 문제에 돈을 지불할 것이다” — 아직은 내 생각",
    svCheckDoneLabel: "“이 문제는 실제로 존재한다” — 찾은 증거로 뒷받침됨",
    mechanismEyebrow: "하이포라가 생각하는 방식",
    notEyebrow: "하이포라는",
    visionEyebrow: "하이포라의 방향",
  },
  dashboard: {
    title: "내 프로젝트",
    subtitle: "지금 진행 중인 모든 아이디어를 한곳에서.",
    newProject: "새 프로젝트",
    projectNameLabel: "프로젝트 이름",
    projectNamePlaceholder: "예: 동네 도구 대여 앱",
    projectDescriptionLabel: "설명 (선택)",
    projectDescriptionHint: "더 많이 알려주실수록 시작 제안이 더 정확해져요.",
    projectDescriptionPlaceholder: "예: 이웃끼리 잘 쓰지 않는 도구를 빌려주고 빌릴 수 있게 도와줘요.",
    emptyTitle: "아직 프로젝트가 없습니다",
    emptyDescription: "아이디어 하나로 시작하세요 — 나중에 더 추가할 수 있어요.",
    open: "열기",
    showArchived: "보관된 프로젝트 보기",
    hideArchived: "보관된 프로젝트 숨기기",
    archiveConfirmTitle: "이 프로젝트를 보관하시겠습니까?",
    archiveConfirmDescription: "프로젝트가 삭제되지 않습니다 — 언제든지 다시 꺼내볼 수 있습니다.",
    loadingProjects: "프로젝트를 불러오는 중…",
  },
  businessStructuring: {
    title: "아이디어 설명하기",
    subtitle: "한 번에 하나씩, 서두르지 않아도 괜찮아요.",
    progressLabel: (current, total) => `${total}개 중 ${current}번째 질문`,
    continueToReview: "검토로 이동",
    reviewTitle: "답변 검토하기",
    reviewSubtitle: "모든 내용을 한곳에서 — 확정하기 전에 무엇이든 수정하세요.",
    riskNotesLabel: "리스크 메모 (선택)",
    riskNotesHint: "무엇이 잘못될 수 있을까요? 이건 당신만을 위한 것이고, 완료를 막지 않아요.",
    confirmAndContinue: "첫 버전으로 이동",
    loadingProject: "프로젝트를 불러오는 중…",
    guardedNotice: "테스트를 시작하려면 먼저 아이디어 설명과 첫 버전 계획을 마쳐야 합니다.",
    onboardingGeneratingTitle: "아이디어를 분석하고 제안을 준비하는 중…",
    onboardingGeneratingHint: "프로젝트를 바탕으로 예시를 만들고 있어요. 준비되기 전에도 직접 답을 작성할 수 있습니다.",
    onboardingFallbackNote: "일반적인 예시입니다 — 언제든지 직접 답을 작성하세요.",
  },
  riskMemo: {
    title: "리스크 & 아직 모르는 것",
    subtitle: "무엇이 잘못될 수 있는지, 아직 확신이 없는 부분을 적어보세요. 모두 선택 사항입니다.",
    technicalRisksLabel: "만드는 과정에서 잘못될 수 있는 것",
    businessRisksLabel: "아이디어 자체에서 잘못될 수 있는 것",
    openQuestionsLabel: "아직 모르는 것",
  },
  question: {
    businessIdea: {
      title: "아이디어를 한두 문장으로 설명해 주세요.",
      presets: [
        "[대상]이 [일]을 더 쉽게 할 수 있도록 돕는 구독 서비스.",
        "[그룹 A]와 [그룹 B]를 연결하는 마켓플레이스.",
        "[대상]을 위해 [번거로운 작업]을 자동화하는 도구.",
        "[원하는 것]을 [대상]에게 더 가까이 가져다주는 지역 서비스.",
      ],
    },
    problem: {
      title: "어떤 문제를 해결하려고 하나요? 누구의 문제인가요?",
      presets: [
        "[X]를 쉽게 할 방법이 없어서 사람들이 시간이나 돈을 낭비하고 있습니다.",
        "기존 옵션은 [대상]에게 너무 비싸거나, 느리거나, 불편합니다.",
        "[대상]이 오늘날 [X]를 찾거나 할 수 있는 신뢰할 수 있는 방법이 없습니다.",
      ],
    },
    targetCustomer: {
      title: "구체적으로 누가 이 문제를 겪고 있나요?",
      presets: ["바쁜 도시 직장인", "소상공인", "어린 자녀를 둔 부모", "학생", "새로운 동네나 도시로 이사한 사람"],
    },
    solution: {
      title: "무엇을 만들려고 하나요?",
      presets: [
        "[대상]을 [자원]과 직접 연결하는 모바일 앱.",
        "[수동 프로세스]를 자동화하는 간단한 웹 도구.",
        "신뢰·안전 기능이 내장된 큐레이션 마켓플레이스.",
      ],
    },
    valueProposition: {
      title: "사람들이 다른 대안 대신 이것을 선택하는 이유는 무엇인가요?",
      presets: [
        "기존 대안보다 시간을 절약해 줍니다.",
        "기존 옵션보다 비용이 적게 듭니다.",
        "다른 어떤 것도 하지 못하는 방식으로 신뢰와 커뮤니티를 만듭니다.",
        "경쟁자가 제공하지 못하는 때와 장소에서 이용할 수 있어 더 편리합니다.",
      ],
    },
  },
  mvpPlanning: {
    title: "첫 버전 계획하기",
    subtitle: "무엇을 먼저 만들지, 그리고 무엇이 필요한지 정하세요.",
    scopeLabel: "먼저 만들 것",
    scopeHint: "무엇을 먼저 만들고, 무엇은 나중으로 미룰 건가요?",
    markScopeComplete: "만들 것 결정 완료",
    markedComplete: "결정됨 ✓",
    featurePlanningTitle: "기능 목록",
    addFeatureLabel: "기능 추가",
    addFeaturePlaceholder: "예: 카테고리별 검색",
    add: "추가",
    remove: "제거",
    emptyFeaturesTitle: "아직 아무것도 없습니다",
    emptyFeaturesDescription: "만들고 싶은 첫 번째 기능을 추가하세요.",
    markFeaturePlanningComplete: "기능 목록 완료",
    priorityMust: "꼭 필요",
    priorityShould: "있으면 좋음",
    priorityCould: "나중에",
    inScope: "만들 것",
    outOfScope: "만들지 않을 것",
    readyForValidation: "테스트 준비 완료",
    suggestFeaturesLabel: "기능 제안받기",
    suggestedFeaturesTitle: "AI가 제안한 기능",
    suggestedFeaturesEmptyNotice: "지금은 AI가 제안할 새로운 아이디어가 없습니다.",
    duplicateIndicator: "이미 계획에 있음",
    featuresAddedLabel: (count) => `기능 ${count}개 추가됨`,
    historyToggleLabel: "히스토리",
    historyTitle: "기능 목록 변경 내역",
    historyEmptyDescription: "아직 기록된 기능 변경 사항이 없습니다.",
    historyCreatedLabel: "추가됨",
    historyRemovedLabel: "제거됨",
    historyAnnotationPlaceholder: "선택적으로 메모를 추가하세요…",
  },
  validationPlanning: {
    title: "아이디어 테스트하기",
    subtitle: "당신이 믿는 것을 테스트할 수 있는 항목으로 바꾸세요.",
    reopenMvpPlanning: "돌아가서 만들 것 다시 정하기",
    addAssumptionLabel: "테스트할 것 추가",
    addAssumptionPlaceholder: "예: 고객이 이 서비스에 월 1만원을 지불할 것이다",
    add: "추가",
    emptyTitle: "아직 테스트할 것이 없습니다",
    emptyDescription: "이 아이디어를 테스트 완료로 표시하려면 최소 하나를 추가하세요.",
    methodLabel: "확인 방법",
    methodPlaceholder: "이것을 어떻게 확인할 건가요?",
    criterionLabel: "무엇을 보면 알 수 있는지",
    criterionPlaceholder: "어떤 결과가 나오면 잘 되고 있다고 볼 건가요?",
    statusOpen: "아직 테스트 전",
    statusValidated: "뒷받침됨",
    statusInvalidated: "뒷받침되지 않음",
    markValidated: "뒷받침됨으로 표시",
    markInvalidated: "뒷받침되지 않음으로 표시",
    notReadyNotice: "테스트를 시작하려면 먼저 아이디어 설명과 첫 버전 계획을 마쳐야 합니다.",
    allResolvedNotice: "모두 테스트를 마쳤습니다 — 개요에서 계획을 완료로 표시하세요",
  },
  projectSummary: {
    title: "개요",
    subtitle: "계획이 얼마나 완성됐는지 확인하세요.",
    businessCanvasTitle: "아이디어 설명",
    fieldsCompleted: (done, total) => `${total}개 중 ${done}개 항목 완료`,
    mvpPlanningTitle: "첫 버전",
    mvpPlanningStatus: (scopeComplete, featureCount, planningComplete) =>
      `만들 것 ${scopeComplete ? "완료" : "진행 중"} · 기능 ${featureCount}개 · 기능 목록 ${planningComplete ? "완료" : "진행 중"}`,
    validationPlanningTitle: "테스트",
    validationStatus: (resolved, total) => `${total}개 중 ${resolved}개 테스트 완료`,
    confirmBuildReady: "계획 완료로 표시",
    isBuildReady: "이 프로젝트의 계획이 완료되었습니다",
    blockingCanvas: "계속하려면 아이디어에 대한 다섯 가지 질문을 모두 완료하세요.",
    blockingScope: "먼저 만들 것을 결정 완료로 표시하세요.",
    blockingFeaturePlanning: "기능 목록을 완료로 표시하세요.",
    blockingValidationEmpty: "테스트할 것을 최소 하나 추가하세요.",
    blockingValidationOpen: "목록에 남은 모든 테스트를 마치세요.",
    blockingConfirm: "준비가 되면 이 프로젝트의 계획을 완료로 표시하세요.",
    goToCanvas: "아이디어로 이동",
    goToMvpPlanning: "첫 버전으로 이동",
    goToValidationPlanning: "테스트로 이동",
    summaryCardTitle: "아이디어 요약",
    summaryNotGenerated: "아이디어 설명을 마치면 AI가 자동으로 요약을 작성합니다.",
    summaryGenerating: "아이디어 요약을 작성하는 중입니다…",
    summaryOutOfSyncBadge: "업데이트 필요",
    summaryOutOfSyncNotice: "이 요약은 최근 변경 사항이 반영되기 전에 작성되었습니다. 업데이트하기 전까지는 아래 내용이 그대로 표시됩니다.",
    syncSummaryButton: "요약 새로 받기",
    syncDialogTitle: "아이디어 요약 업데이트",
    syncDialogAsIsLabel: "현재 버전",
    syncDialogToBeLabel: "새 초안",
    syncDialogToBeEmptyHint: "아래 버튼을 눌러 AI가 새 초안을 작성하게 하세요 — 저장하기 전에 자유롭게 수정할 수 있습니다.",
    aiSummaryUpdateButton: "AI에게 다시 써달라고 하기",
    applyButton: "저장",
  },
  aiAssistant: {
    askAiLabel: "AI에게 아이디어 받기",
    aiTag: "AI",
    loadingLabel: "AI가 생각하는 중…",
    acceptLabel: "적용",
    rejectLabel: "괜찮아요",
    regenerateLabel: "다시 받기",
    retryLabel: "다시 시도",
    appliedLabel: "추가됨",
    failureGeneric: "지금은 AI가 떠올릴 게 없나 봐요 — 직접 계속 작성할 수 있습니다.",
    failureTimeout: "시간이 좀 걸리고 있어요. 다시 시도하거나, 그냥 직접 작성해 보세요.",
    failureRateLimited: "지금 AI가 바쁜가 봐요. 잠시 후 다시 시도하거나, 계속 작성해 보세요.",
    failureUnavailable: "지금은 AI를 사용할 수 없어요 — AI 없이 계속 진행할 수 있습니다.",
    failureSafetyRefusal: "여기서는 AI가 제안할 게 없어요 — 직접 답변을 계속 작성하세요.",
  },
  errors: {
    projectNotFound: "프로젝트를 찾을 수 없습니다.",
    saveFailed: "마지막 변경사항을 저장하지 못했습니다. 다시 시도해 주세요.",
  },
};
